# CMake generated Testfile for 
# Source directory: /tmp/nes-1699-tidy/nes-frontend/apps
# Build directory: /tmp/nes-1699-tidy/build-rel/nes-frontend/apps
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[embedded-repl-test]=] "env" "NES_DIR=/tmp/nes-1699-tidy" "env" "NES_TEST_TMP_DIR=/tmp/nes-1699-tidy/build-rel/test-tmp" "env" "NES_BATS_LIB=/tmp/nes-1699-tidy/scripts/testing/distributed_bats_lib.bash" "env" "NES_WORKER=/tmp/nes-1699-tidy/build-rel/nes-single-node-worker/nes-single-node-worker" "env" "NES_CLI=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-cli" "env" "NES_REPL=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl" "env" "NES_REPL_EMBEDDED=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl-embedded" "env" "NES_SYSTEST=/tmp/nes-1699-tidy/build-rel/nes-systests/systest/systest" "/usr/bin/bats" "--verbose-run" "--timing" "/tmp/nes-1699-tidy/nes-frontend/apps/repl/tests/embedded.bats")
set_tests_properties([=[embedded-repl-test]=] PROPERTIES  FIXTURES_REQUIRED "E2eBinaries" LABELS "" _BACKTRACE_TRIPLES "/tmp/nes-1699-tidy/cmake/macros.cmake;185;add_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;47;add_e2e_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;0;")
add_test([=[offline-cli-test]=] "env" "NES_DIR=/tmp/nes-1699-tidy" "env" "NES_TEST_TMP_DIR=/tmp/nes-1699-tidy/build-rel/test-tmp" "env" "NES_BATS_LIB=/tmp/nes-1699-tidy/scripts/testing/distributed_bats_lib.bash" "env" "NES_WORKER=/tmp/nes-1699-tidy/build-rel/nes-single-node-worker/nes-single-node-worker" "env" "NES_CLI=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-cli" "env" "NES_REPL=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl" "env" "NES_REPL_EMBEDDED=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl-embedded" "env" "NES_SYSTEST=/tmp/nes-1699-tidy/build-rel/nes-systests/systest/systest" "/usr/bin/bats" "--verbose-run" "--timing" "/tmp/nes-1699-tidy/nes-frontend/apps/cli/tests/offline.bats")
set_tests_properties([=[offline-cli-test]=] PROPERTIES  FIXTURES_REQUIRED "E2eBinaries" LABELS "" _BACKTRACE_TRIPLES "/tmp/nes-1699-tidy/cmake/macros.cmake;185;add_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;52;add_e2e_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;0;")
add_test([=[distributed-cli-test]=] "env" "NES_DIR=/tmp/nes-1699-tidy" "env" "NES_TEST_TMP_DIR=/tmp/nes-1699-tidy/build-rel/test-tmp" "env" "NES_BATS_LIB=/tmp/nes-1699-tidy/scripts/testing/distributed_bats_lib.bash" "env" "NES_WORKER=/tmp/nes-1699-tidy/build-rel/nes-single-node-worker/nes-single-node-worker" "env" "NES_CLI=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-cli" "env" "NES_REPL=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl" "env" "NES_REPL_EMBEDDED=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl-embedded" "env" "NES_SYSTEST=/tmp/nes-1699-tidy/build-rel/nes-systests/systest/systest" "env" "NES_RUNTIME_BASE_IMAGE=nes-runtime-base:test" "/usr/bin/bats" "--verbose-run" "--timing" "--jobs" "4" "/tmp/nes-1699-tidy/nes-frontend/apps/cli/tests/distributed.bats")
set_tests_properties([=[distributed-cli-test]=] PROPERTIES  FIXTURES_REQUIRED "E2eBinaries;RuntimeBaseImage" LABELS "DockerCompose" _BACKTRACE_TRIPLES "/tmp/nes-1699-tidy/cmake/macros.cmake;185;add_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;58;add_e2e_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;0;")
add_test([=[distributed-repl-tests]=] "env" "NES_DIR=/tmp/nes-1699-tidy" "env" "NES_TEST_TMP_DIR=/tmp/nes-1699-tidy/build-rel/test-tmp" "env" "NES_BATS_LIB=/tmp/nes-1699-tidy/scripts/testing/distributed_bats_lib.bash" "env" "NES_WORKER=/tmp/nes-1699-tidy/build-rel/nes-single-node-worker/nes-single-node-worker" "env" "NES_CLI=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-cli" "env" "NES_REPL=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl" "env" "NES_REPL_EMBEDDED=/tmp/nes-1699-tidy/build-rel/nes-frontend/apps/nes-repl-embedded" "env" "NES_SYSTEST=/tmp/nes-1699-tidy/build-rel/nes-systests/systest/systest" "env" "NES_RUNTIME_BASE_IMAGE=nes-runtime-base:test" "/usr/bin/bats" "--verbose-run" "--timing" "/tmp/nes-1699-tidy/nes-frontend/apps/repl/tests/distributed.bats")
set_tests_properties([=[distributed-repl-tests]=] PROPERTIES  FIXTURES_REQUIRED "E2eBinaries;RuntimeBaseImage" LABELS "DockerCompose" _BACKTRACE_TRIPLES "/tmp/nes-1699-tidy/cmake/macros.cmake;185;add_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;65;add_e2e_test;/tmp/nes-1699-tidy/nes-frontend/apps/CMakeLists.txt;0;")
