CREATE LOGICAL SOURCE endless(val_1 UINT32, ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
    'ALL' as "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    'CSV' as INPUT_FORMATTER."TYPE",
    'SEQUENCE UINT32 0 10000000 1, SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);
SELECT TS FROM ENDLESS INTO Void('localhost:8080' AS "SINK"."HOST");
SELECT * FROM ENDLESS INTO Void('localhost:8080' AS "SINK"."HOST");
SELECT val_1 + 1 AS val_plus_1 FROM ENDLESS INTO Void('localhost:8080' AS "SINK"."HOST");
SELECT AVG(val_1) AS agg_val_1 FROM ENDLESS WINDOW TUMBLING(ts, SIZE 1 SEC) INTO Void('localhost:8080' AS "SINK"."HOST");
