/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include <Sinks/SinkCatalog.hpp>

#include <algorithm>
#include <cctype>
#include <optional>
#include <ranges>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>
#include <DataTypes/Schema.hpp>
#include <Sinks/SinkDescriptor.hpp>
#include <Util/Logger/Logger.hpp>

namespace NES
{

std::optional<SinkDescriptor> SinkCatalog::addSinkDescriptor(
    std::string sinkName,
    const Schema& schema,
    const std::string_view sinkType,
    std::unordered_map<std::string, std::string> config,
    const std::unordered_map<std::string, std::string>& formatConfig)
{
    if (std::ranges::all_of(sinkName, [](const char character) { return std::isdigit(character); }))
    {
        /// Reserve number names for the future where we might want to have inlined sink descriptor declarations in queries again, which requires autogenerating some identifier.
        NES_DEBUG("Sink name {} is invalid, only-digit names are reserved for autogenerated names", sinkName);
        return std::nullopt;
    }

    auto descriptorConfigOpt = SinkDescriptor::validateAndFormatConfig(sinkType, std::move(config));
    if (not descriptorConfigOpt.has_value())
    {
        return std::nullopt;
    }

    const auto lockedSinks = sinks.wlock();
    auto sinkDescriptor = SinkDescriptor{sinkName, schema, sinkType, formatConfig, std::move(descriptorConfigOpt.value())};
    lockedSinks->emplace(toUpperCase(sinkName), sinkDescriptor);
    return sinkDescriptor;
}

std::optional<SinkDescriptor> SinkCatalog::getSinkDescriptor(const std::string& sinkName) const
{
    const auto lockedSinks = sinks.rlock();
    const auto sinkDescriptorOpt = lockedSinks->find(std::string{sinkName});
    if (sinkDescriptorOpt == lockedSinks->end())
    {
        return std::nullopt;
    }
    return sinkDescriptorOpt->second;
}

std::optional<SinkDescriptor> SinkCatalog::getInlineSink(
    const Schema& schema,
    std::string_view sinkType,
    std::unordered_map<std::string, std::string> config,
    const std::unordered_map<std::string, std::string>& formatConfig) const
{
    auto descriptorConfigOpt = SinkDescriptor::validateAndFormatConfig(sinkType, std::move(config));

    const auto inlineSinkId = InlineSinkId{nextInlineSinkId.fetch_add(1)};

    if (not descriptorConfigOpt.has_value())
    {
        return std::nullopt;
    }

    auto sinkDescriptor
        = SinkDescriptor{inlineSinkId.getRawValue(), schema, sinkType, formatConfig, std::move(descriptorConfigOpt.value())};

    return sinkDescriptor;
}

bool SinkCatalog::removeSinkDescriptor(const std::string& sinkName)
{
    const auto lockedSinks = sinks.wlock();
    return lockedSinks->erase(sinkName) == 1;
}

bool SinkCatalog::removeSinkDescriptor(const SinkDescriptor& sinkDescriptor)
{
    const auto lockedSinks = sinks.wlock();
    return lockedSinks->erase(sinkDescriptor.getSinkName()) == 1;
}

bool SinkCatalog::containsSinkDescriptor(const std::string& sinkName) const
{
    const auto lockedSinks = sinks.rlock();
    return lockedSinks->contains(sinkName);
}

bool SinkCatalog::containsSinkDescriptor(const SinkDescriptor& sinkDescriptor) const
{
    const auto lockedSinks = sinks.rlock();
    return lockedSinks->contains(sinkDescriptor.getSinkName());
}

std::vector<SinkDescriptor> SinkCatalog::getAllSinkDescriptors() const
{
    const auto lockedSinks = sinks.rlock();
    return *lockedSinks | std::ranges::views::transform([](const auto& sinkDescriptor) { return sinkDescriptor.second; })
        | std::ranges::to<std::vector>();
}
}
