-- test comment
CREATE WORKER 'worker-node:8080' SET ('worker-node:9090' AS DATA);
CREATE LOGICAL SOURCE endless(ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
       'ALL' as "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
       'CSV' as INPUT_FORMATTER."TYPE",
       10000 AS "SOURCE".MAX_RUNTIME_MS,
       'worker-node:8080' AS "SOURCE"."HOST",
       'emit_rate 10' AS "SOURCE".GENERATOR_RATE_CONFIG,
       1 AS "SOURCE".SEED,
       'SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);
SELECT TS FROM ENDLESS INTO Void('worker-node:8080' AS "SINK"."HOST");
