-- test comment
CREATE LOGICAL SOURCE endless(ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
       'ALL' as `SOURCE`.STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
       'CSV' as PARSER.`TYPE`,
       10000000 AS `SOURCE`.MAX_RUNTIME_MS,
       'emit_rate 10' AS `SOURCE`.GENERATOR_RATE_CONFIG,
       1 AS `SOURCE`.SEED,
       'SEQUENCE UINT64 0 10000000 1' AS `SOURCE`.GENERATOR_SCHEMA);
CREATE SINK someSink(ENDLESS.TS UINT64) TYPE File SET('out.csv' as `SINK`.FILE_PATH, 'CSV' as `SINK`.OUTPUT_FORMAT);
SHOW QUERIES;
SELECT TS FROM ENDLESS INTO SOMESINK SET (1 AS `QUERY`.`ID`);

SHOW QUERIES WHERE id = 1;
DROP QUERY WHERE id = 1;

SHOW QUERIES;
