# Topology:
#
#   ┌──────────────────────────┐     ┌──────────────────────────┐
#   │ source-node:8080 (S)(K)  │────►│ sink-node:8080 (K)       │
#   │ capacity: 8              │     │ capacity: 10000          │
#   └──────────────────────────┘     └──────────────────────────┘
#
workers:
  - host: "sink-node:8080"
    data_address: "sink-node:9090"
    max_operators: 10000
    config:
      worker:
        total_memory_in_bytes: 16384000000
        unpooled_memory_fraction: 0.5
        query_engine:
          number_of_worker_threads: 8

  - host: "source-node:8080"
    data_address: "source-node:9090"
    max_operators: 8
    downstream:
      - "sink-node:8080"
    config:
      worker:
        total_memory_in_bytes: 16384000000
        unpooled_memory_fraction: 0.5
        query_engine:
          number_of_worker_threads: 4

allow_source_placement:
  - "source-node:8080"

allow_sink_placement:
  - "sink-node:8080"
  - "source-node:8080"
