/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

/// NOLINT(clang-diagnostic-error)
#ifndef INCLUDED_FROM_SOURCES_FILE_DATA_REGISTRY
#    error "This file should not be included directly! Include instead include FileDataRegistry.hpp"
#endif

#include <string>
#include <Util/Registry.hpp>

namespace NES::FileDataGeneratedRegistrar
{

/// declarations of register functions for 'SystestAdaptors'
FileDataRegistryReturnType RegisterTCPFileData(FileDataRegistryArguments);
FileDataRegistryReturnType RegisterFileFileData(FileDataRegistryArguments);

}

namespace NES
{
template <>
inline void
Registrar<FileDataRegistry, std::string, FileDataRegistryReturnType, FileDataRegistryArguments>::registerAll(
    [[maybe_unused]] Registry<Registrar>& registry)
{
    using namespace NES::FileDataGeneratedRegistrar;
    registry.addEntry("TCP", RegisterTCPFileData);
	registry.addEntry("File", RegisterFileFileData);
	
}
}
