/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

/// NOLINT(clang-diagnostic-error)
#ifndef INCLUDED_FROM_SOURCE_REGISTRY
#    error "This file should not be included directly! Include instead include SourceRegistry.hpp"
#endif

#include <memory>
#include <string>
#include <Sources/Source.hpp>
#include <Sources/SourceDescriptor.hpp>
#include <Util/Registry.hpp>

namespace NES::SourceGeneratedRegistrar
{

/// declaration of register functions for 'Sources'
SourceRegistryReturnType RegisterTCPSource(SourceRegistryArguments);
SourceRegistryReturnType RegisterGeneratorSource(SourceRegistryArguments);
SourceRegistryReturnType RegisterFileSource(SourceRegistryArguments);
SourceRegistryReturnType RegisterNetworkSource(SourceRegistryArguments);

}

namespace NES
{
template <>
inline void
Registrar<SourceRegistry, std::string, SourceRegistryReturnType, SourceRegistryArguments>::registerAll([[maybe_unused]] Registry<Registrar>& registry)
{

    using namespace NES::SourceGeneratedRegistrar;
    /// the SourceRegistry calls registerAll and thereby all the below functions that register Sources in the SourceRegistry
    registry.addEntry("TCP", RegisterTCPSource);
	registry.addEntry("Generator", RegisterGeneratorSource);
	registry.addEntry("File", RegisterFileSource);
	registry.addEntry("Network", RegisterNetworkSource);
	
}
}
