/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

/// NOLINT(clang-diagnostic-error)
#ifndef INCLUDED_FROM_SOURCE_VALIDATION_REGISTRY
#    error "This file should not be included directly! Include instead include SourceRegistry.hpp"
#endif

#include <memory>
#include <string>
#include <unordered_map>
#include <Sources/SourceDescriptor.hpp>
#include <Util/Registry.hpp>

namespace NES
{

/// declaration of register functions for 'Sources'
SourceValidationRegistryReturnType RegisterTCPSourceValidation(SourceValidationRegistryArguments);
SourceValidationRegistryReturnType RegisterGeneratorSourceValidation(SourceValidationRegistryArguments);
SourceValidationRegistryReturnType RegisterFileSourceValidation(SourceValidationRegistryArguments);
SourceValidationRegistryReturnType RegisterNetworkSourceValidation(SourceValidationRegistryArguments);

}

namespace NES
{

template <>
inline void
Registrar<SourceValidationRegistry, std::string, SourceValidationRegistryReturnType, SourceValidationRegistryArguments>::registerAll(Registry<Registrar>& registry)
{
    using namespace NES;
    registry.addEntry("TCP", RegisterTCPSourceValidation);
	registry.addEntry("Generator", RegisterGeneratorSourceValidation);
	registry.addEntry("File", RegisterFileSourceValidation);
	registry.addEntry("Network", RegisterNetworkSourceValidation);
	
}
}
