// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableIdentifier.proto
// Protobuf C++ Version: 5.29.5

#include "SerializableIdentifier.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NES {

inline constexpr SerializableIdentifier::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        casesensitive_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableIdentifier::SerializableIdentifier(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableIdentifierDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableIdentifierDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableIdentifierDefaultTypeInternal() {}
  union {
    SerializableIdentifier _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableIdentifierDefaultTypeInternal _SerializableIdentifier_default_instance_;

inline constexpr SerializableIdentifierList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : identifiers_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableIdentifierList::SerializableIdentifierList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableIdentifierListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableIdentifierListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableIdentifierListDefaultTypeInternal() {}
  union {
    SerializableIdentifierList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableIdentifierListDefaultTypeInternal _SerializableIdentifierList_default_instance_;
}  // namespace NES
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SerializableIdentifier_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SerializableIdentifier_2eproto = nullptr;
const ::uint32_t
    TableStruct_SerializableIdentifier_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableIdentifier, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableIdentifier, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableIdentifier, _impl_.casesensitive_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableIdentifierList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableIdentifierList, _impl_.identifiers_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NES::SerializableIdentifier)},
        {10, -1, -1, sizeof(::NES::SerializableIdentifierList)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NES::_SerializableIdentifier_default_instance_._instance,
    &::NES::_SerializableIdentifierList_default_instance_._instance,
};
const char descriptor_table_protodef_SerializableIdentifier_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034SerializableIdentifier.proto\022\003NES\">\n\026S"
    "erializableIdentifier\022\r\n\005value\030\001 \001(\t\022\025\n\r"
    "caseSensitive\030\002 \001(\010\"N\n\032SerializableIdent"
    "ifierList\0220\n\013identifiers\030\001 \003(\0132\033.NES.Ser"
    "ializableIdentifierb\006proto3"
};
static ::absl::once_flag descriptor_table_SerializableIdentifier_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SerializableIdentifier_2eproto = {
    false,
    false,
    187,
    descriptor_table_protodef_SerializableIdentifier_2eproto,
    "SerializableIdentifier.proto",
    &descriptor_table_SerializableIdentifier_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_SerializableIdentifier_2eproto::offsets,
    file_level_enum_descriptors_SerializableIdentifier_2eproto,
    file_level_service_descriptors_SerializableIdentifier_2eproto,
};
namespace NES {
// ===================================================================

class SerializableIdentifier::_Internal {
 public:
};

SerializableIdentifier::SerializableIdentifier(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableIdentifier)
}
inline PROTOBUF_NDEBUG_INLINE SerializableIdentifier::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableIdentifier& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

SerializableIdentifier::SerializableIdentifier(
    ::google::protobuf::Arena* arena,
    const SerializableIdentifier& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableIdentifier* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.casesensitive_ = from._impl_.casesensitive_;

  // @@protoc_insertion_point(copy_constructor:NES.SerializableIdentifier)
}
inline PROTOBUF_NDEBUG_INLINE SerializableIdentifier::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void SerializableIdentifier::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.casesensitive_ = {};
}
SerializableIdentifier::~SerializableIdentifier() {
  // @@protoc_insertion_point(destructor:NES.SerializableIdentifier)
  SharedDtor(*this);
}
inline void SerializableIdentifier::SharedDtor(MessageLite& self) {
  SerializableIdentifier& this_ = static_cast<SerializableIdentifier&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SerializableIdentifier::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableIdentifier(arena);
}
constexpr auto SerializableIdentifier::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SerializableIdentifier),
                                            alignof(SerializableIdentifier));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableIdentifier::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableIdentifier_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableIdentifier::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableIdentifier>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableIdentifier::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableIdentifier>(), &SerializableIdentifier::ByteSizeLong,
            &SerializableIdentifier::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableIdentifier, _impl_._cached_size_),
        false,
    },
    &SerializableIdentifier::kDescriptorMethods,
    &descriptor_table_SerializableIdentifier_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableIdentifier::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> SerializableIdentifier::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableIdentifier>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool caseSensitive = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SerializableIdentifier, _impl_.casesensitive_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableIdentifier, _impl_.casesensitive_)}},
    // string value = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableIdentifier, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableIdentifier, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool caseSensitive = 2;
    {PROTOBUF_FIELD_OFFSET(SerializableIdentifier, _impl_.casesensitive_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\32\5\0\0\0\0\0\0"
    "NES.SerializableIdentifier"
    "value"
  }},
};

PROTOBUF_NOINLINE void SerializableIdentifier::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableIdentifier)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _impl_.casesensitive_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableIdentifier::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableIdentifier& this_ = static_cast<const SerializableIdentifier&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableIdentifier::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableIdentifier& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableIdentifier)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string value = 1;
          if (!this_._internal_value().empty()) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableIdentifier.value");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool caseSensitive = 2;
          if (this_._internal_casesensitive() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_casesensitive(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableIdentifier)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableIdentifier::ByteSizeLong(const MessageLite& base) {
          const SerializableIdentifier& this_ = static_cast<const SerializableIdentifier&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableIdentifier::ByteSizeLong() const {
          const SerializableIdentifier& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableIdentifier)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string value = 1;
            if (!this_._internal_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
            // bool caseSensitive = 2;
            if (this_._internal_casesensitive() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableIdentifier::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableIdentifier*>(&to_msg);
  auto& from = static_cast<const SerializableIdentifier&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableIdentifier)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  if (from._internal_casesensitive() != 0) {
    _this->_impl_.casesensitive_ = from._impl_.casesensitive_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableIdentifier::CopyFrom(const SerializableIdentifier& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableIdentifier)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableIdentifier::InternalSwap(SerializableIdentifier* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
        swap(_impl_.casesensitive_, other->_impl_.casesensitive_);
}

::google::protobuf::Metadata SerializableIdentifier::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SerializableIdentifierList::_Internal {
 public:
};

SerializableIdentifierList::SerializableIdentifierList(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableIdentifierList)
}
inline PROTOBUF_NDEBUG_INLINE SerializableIdentifierList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableIdentifierList& from_msg)
      : identifiers_{visibility, arena, from.identifiers_},
        _cached_size_{0} {}

SerializableIdentifierList::SerializableIdentifierList(
    ::google::protobuf::Arena* arena,
    const SerializableIdentifierList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableIdentifierList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:NES.SerializableIdentifierList)
}
inline PROTOBUF_NDEBUG_INLINE SerializableIdentifierList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : identifiers_{visibility, arena},
        _cached_size_{0} {}

inline void SerializableIdentifierList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SerializableIdentifierList::~SerializableIdentifierList() {
  // @@protoc_insertion_point(destructor:NES.SerializableIdentifierList)
  SharedDtor(*this);
}
inline void SerializableIdentifierList::SharedDtor(MessageLite& self) {
  SerializableIdentifierList& this_ = static_cast<SerializableIdentifierList&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SerializableIdentifierList::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableIdentifierList(arena);
}
constexpr auto SerializableIdentifierList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SerializableIdentifierList, _impl_.identifiers_) +
          decltype(SerializableIdentifierList::_impl_.identifiers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SerializableIdentifierList), alignof(SerializableIdentifierList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SerializableIdentifierList::PlacementNew_,
                                 sizeof(SerializableIdentifierList),
                                 alignof(SerializableIdentifierList));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableIdentifierList::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableIdentifierList_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableIdentifierList::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableIdentifierList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableIdentifierList::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableIdentifierList>(), &SerializableIdentifierList::ByteSizeLong,
            &SerializableIdentifierList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableIdentifierList, _impl_._cached_size_),
        false,
    },
    &SerializableIdentifierList::kDescriptorMethods,
    &descriptor_table_SerializableIdentifier_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableIdentifierList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SerializableIdentifierList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableIdentifierList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .NES.SerializableIdentifier identifiers = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableIdentifierList, _impl_.identifiers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .NES.SerializableIdentifier identifiers = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableIdentifierList, _impl_.identifiers_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::NES::SerializableIdentifier>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SerializableIdentifierList::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableIdentifierList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.identifiers_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableIdentifierList::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableIdentifierList& this_ = static_cast<const SerializableIdentifierList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableIdentifierList::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableIdentifierList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableIdentifierList)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .NES.SerializableIdentifier identifiers = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_identifiers_size());
               i < n; i++) {
            const auto& repfield = this_._internal_identifiers().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableIdentifierList)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableIdentifierList::ByteSizeLong(const MessageLite& base) {
          const SerializableIdentifierList& this_ = static_cast<const SerializableIdentifierList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableIdentifierList::ByteSizeLong() const {
          const SerializableIdentifierList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableIdentifierList)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .NES.SerializableIdentifier identifiers = 1;
            {
              total_size += 1UL * this_._internal_identifiers_size();
              for (const auto& msg : this_._internal_identifiers()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableIdentifierList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableIdentifierList*>(&to_msg);
  auto& from = static_cast<const SerializableIdentifierList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableIdentifierList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_identifiers()->MergeFrom(
      from._internal_identifiers());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableIdentifierList::CopyFrom(const SerializableIdentifierList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableIdentifierList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableIdentifierList::InternalSwap(SerializableIdentifierList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.identifiers_.InternalSwap(&other->_impl_.identifiers_);
}

::google::protobuf::Metadata SerializableIdentifierList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SerializableIdentifier_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
