// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableQueryId.proto
// Protobuf C++ Version: 5.29.5

#ifndef SerializableQueryId_2eproto_2epb_2eh
#define SerializableQueryId_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SerializableQueryId_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SerializableQueryId_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SerializableQueryId_2eproto;
namespace NES {
class SerializableQueryId;
struct SerializableQueryIdDefaultTypeInternal;
extern SerializableQueryIdDefaultTypeInternal _SerializableQueryId_default_instance_;
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NES {

// ===================================================================


// -------------------------------------------------------------------

class SerializableQueryId final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableQueryId) */ {
 public:
  inline SerializableQueryId() : SerializableQueryId(nullptr) {}
  ~SerializableQueryId() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableQueryId* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableQueryId));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableQueryId(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableQueryId(const SerializableQueryId& from) : SerializableQueryId(nullptr, from) {}
  inline SerializableQueryId(SerializableQueryId&& from) noexcept
      : SerializableQueryId(nullptr, std::move(from)) {}
  inline SerializableQueryId& operator=(const SerializableQueryId& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableQueryId& operator=(SerializableQueryId&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableQueryId& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableQueryId* internal_default_instance() {
    return reinterpret_cast<const SerializableQueryId*>(
        &_SerializableQueryId_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SerializableQueryId& a, SerializableQueryId& b) { a.Swap(&b); }
  inline void Swap(SerializableQueryId* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableQueryId* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableQueryId* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableQueryId>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableQueryId& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableQueryId& from) { SerializableQueryId::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableQueryId* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableQueryId"; }

 protected:
  explicit SerializableQueryId(::google::protobuf::Arena* arena);
  SerializableQueryId(::google::protobuf::Arena* arena, const SerializableQueryId& from);
  SerializableQueryId(::google::protobuf::Arena* arena, SerializableQueryId&& from) noexcept
      : SerializableQueryId(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLocalQueryIdFieldNumber = 1,
    kDistributedQueryIdFieldNumber = 2,
  };
  // string local_query_id = 1;
  void clear_local_query_id() ;
  const std::string& local_query_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_local_query_id(Arg_&& arg, Args_... args);
  std::string* mutable_local_query_id();
  PROTOBUF_NODISCARD std::string* release_local_query_id();
  void set_allocated_local_query_id(std::string* value);

  private:
  const std::string& _internal_local_query_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_local_query_id(
      const std::string& value);
  std::string* _internal_mutable_local_query_id();

  public:
  // string distributed_query_id = 2;
  void clear_distributed_query_id() ;
  const std::string& distributed_query_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_distributed_query_id(Arg_&& arg, Args_... args);
  std::string* mutable_distributed_query_id();
  PROTOBUF_NODISCARD std::string* release_distributed_query_id();
  void set_allocated_distributed_query_id(std::string* value);

  private:
  const std::string& _internal_distributed_query_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_distributed_query_id(
      const std::string& value);
  std::string* _internal_mutable_distributed_query_id();

  public:
  // @@protoc_insertion_point(class_scope:NES.SerializableQueryId)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      66, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableQueryId& from_msg);
    ::google::protobuf::internal::ArenaStringPtr local_query_id_;
    ::google::protobuf::internal::ArenaStringPtr distributed_query_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableQueryId_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializableQueryId

// string local_query_id = 1;
inline void SerializableQueryId::clear_local_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.local_query_id_.ClearToEmpty();
}
inline const std::string& SerializableQueryId::local_query_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableQueryId.local_query_id)
  return _internal_local_query_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SerializableQueryId::set_local_query_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.local_query_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NES.SerializableQueryId.local_query_id)
}
inline std::string* SerializableQueryId::mutable_local_query_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_local_query_id();
  // @@protoc_insertion_point(field_mutable:NES.SerializableQueryId.local_query_id)
  return _s;
}
inline const std::string& SerializableQueryId::_internal_local_query_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.local_query_id_.Get();
}
inline void SerializableQueryId::_internal_set_local_query_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.local_query_id_.Set(value, GetArena());
}
inline std::string* SerializableQueryId::_internal_mutable_local_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.local_query_id_.Mutable( GetArena());
}
inline std::string* SerializableQueryId::release_local_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableQueryId.local_query_id)
  return _impl_.local_query_id_.Release();
}
inline void SerializableQueryId::set_allocated_local_query_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.local_query_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.local_query_id_.IsDefault()) {
    _impl_.local_query_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableQueryId.local_query_id)
}

// string distributed_query_id = 2;
inline void SerializableQueryId::clear_distributed_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distributed_query_id_.ClearToEmpty();
}
inline const std::string& SerializableQueryId::distributed_query_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableQueryId.distributed_query_id)
  return _internal_distributed_query_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SerializableQueryId::set_distributed_query_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distributed_query_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NES.SerializableQueryId.distributed_query_id)
}
inline std::string* SerializableQueryId::mutable_distributed_query_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_distributed_query_id();
  // @@protoc_insertion_point(field_mutable:NES.SerializableQueryId.distributed_query_id)
  return _s;
}
inline const std::string& SerializableQueryId::_internal_distributed_query_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.distributed_query_id_.Get();
}
inline void SerializableQueryId::_internal_set_distributed_query_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distributed_query_id_.Set(value, GetArena());
}
inline std::string* SerializableQueryId::_internal_mutable_distributed_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.distributed_query_id_.Mutable( GetArena());
}
inline std::string* SerializableQueryId::release_distributed_query_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableQueryId.distributed_query_id)
  return _impl_.distributed_query_id_.Release();
}
inline void SerializableQueryId::set_allocated_distributed_query_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distributed_query_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.distributed_query_id_.IsDefault()) {
    _impl_.distributed_query_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableQueryId.distributed_query_id)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NES


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SerializableQueryId_2eproto_2epb_2eh
