// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableQueryId.proto
// Protobuf C++ Version: 5.29.5

#include "SerializableQueryId.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NES {

inline constexpr SerializableQueryId::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : local_query_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        distributed_query_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableQueryId::SerializableQueryId(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableQueryIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableQueryIdDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableQueryIdDefaultTypeInternal() {}
  union {
    SerializableQueryId _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableQueryIdDefaultTypeInternal _SerializableQueryId_default_instance_;
}  // namespace NES
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SerializableQueryId_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SerializableQueryId_2eproto = nullptr;
const ::uint32_t
    TableStruct_SerializableQueryId_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryId, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryId, _impl_.local_query_id_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryId, _impl_.distributed_query_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NES::SerializableQueryId)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NES::_SerializableQueryId_default_instance_._instance,
};
const char descriptor_table_protodef_SerializableQueryId_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031SerializableQueryId.proto\022\003NES\"K\n\023Seri"
    "alizableQueryId\022\026\n\016local_query_id\030\001 \001(\t\022"
    "\034\n\024distributed_query_id\030\002 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_SerializableQueryId_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SerializableQueryId_2eproto = {
    false,
    false,
    117,
    descriptor_table_protodef_SerializableQueryId_2eproto,
    "SerializableQueryId.proto",
    &descriptor_table_SerializableQueryId_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SerializableQueryId_2eproto::offsets,
    file_level_enum_descriptors_SerializableQueryId_2eproto,
    file_level_service_descriptors_SerializableQueryId_2eproto,
};
namespace NES {
// ===================================================================

class SerializableQueryId::_Internal {
 public:
};

SerializableQueryId::SerializableQueryId(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableQueryId)
}
inline PROTOBUF_NDEBUG_INLINE SerializableQueryId::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableQueryId& from_msg)
      : local_query_id_(arena, from.local_query_id_),
        distributed_query_id_(arena, from.distributed_query_id_),
        _cached_size_{0} {}

SerializableQueryId::SerializableQueryId(
    ::google::protobuf::Arena* arena,
    const SerializableQueryId& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableQueryId* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:NES.SerializableQueryId)
}
inline PROTOBUF_NDEBUG_INLINE SerializableQueryId::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : local_query_id_(arena),
        distributed_query_id_(arena),
        _cached_size_{0} {}

inline void SerializableQueryId::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SerializableQueryId::~SerializableQueryId() {
  // @@protoc_insertion_point(destructor:NES.SerializableQueryId)
  SharedDtor(*this);
}
inline void SerializableQueryId::SharedDtor(MessageLite& self) {
  SerializableQueryId& this_ = static_cast<SerializableQueryId&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.local_query_id_.Destroy();
  this_._impl_.distributed_query_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SerializableQueryId::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableQueryId(arena);
}
constexpr auto SerializableQueryId::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SerializableQueryId),
                                            alignof(SerializableQueryId));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableQueryId::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableQueryId_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableQueryId::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableQueryId>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableQueryId::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableQueryId>(), &SerializableQueryId::ByteSizeLong,
            &SerializableQueryId::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableQueryId, _impl_._cached_size_),
        false,
    },
    &SerializableQueryId::kDescriptorMethods,
    &descriptor_table_SerializableQueryId_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableQueryId::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 66, 2> SerializableQueryId::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableQueryId>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string distributed_query_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableQueryId, _impl_.distributed_query_id_)}},
    // string local_query_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableQueryId, _impl_.local_query_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string local_query_id = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableQueryId, _impl_.local_query_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string distributed_query_id = 2;
    {PROTOBUF_FIELD_OFFSET(SerializableQueryId, _impl_.distributed_query_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\16\24\0\0\0\0\0"
    "NES.SerializableQueryId"
    "local_query_id"
    "distributed_query_id"
  }},
};

PROTOBUF_NOINLINE void SerializableQueryId::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableQueryId)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.local_query_id_.ClearToEmpty();
  _impl_.distributed_query_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableQueryId::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableQueryId& this_ = static_cast<const SerializableQueryId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableQueryId::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableQueryId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableQueryId)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string local_query_id = 1;
          if (!this_._internal_local_query_id().empty()) {
            const std::string& _s = this_._internal_local_query_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableQueryId.local_query_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string distributed_query_id = 2;
          if (!this_._internal_distributed_query_id().empty()) {
            const std::string& _s = this_._internal_distributed_query_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableQueryId.distributed_query_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableQueryId)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableQueryId::ByteSizeLong(const MessageLite& base) {
          const SerializableQueryId& this_ = static_cast<const SerializableQueryId&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableQueryId::ByteSizeLong() const {
          const SerializableQueryId& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableQueryId)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string local_query_id = 1;
            if (!this_._internal_local_query_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_local_query_id());
            }
            // string distributed_query_id = 2;
            if (!this_._internal_distributed_query_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_distributed_query_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableQueryId::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableQueryId*>(&to_msg);
  auto& from = static_cast<const SerializableQueryId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableQueryId)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_local_query_id().empty()) {
    _this->_internal_set_local_query_id(from._internal_local_query_id());
  }
  if (!from._internal_distributed_query_id().empty()) {
    _this->_internal_set_distributed_query_id(from._internal_distributed_query_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableQueryId::CopyFrom(const SerializableQueryId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableQueryId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableQueryId::InternalSwap(SerializableQueryId* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.local_query_id_, &other->_impl_.local_query_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.distributed_query_id_, &other->_impl_.distributed_query_id_, arena);
}

::google::protobuf::Metadata SerializableQueryId::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SerializableQueryId_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
