// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableDataType.proto
// Protobuf C++ Version: 5.29.5

#include "SerializableDataType.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NES {

inline constexpr SerializableDataType::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::NES::SerializableDataType_Type >(0)},
        nullable_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableDataType::SerializableDataType(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableDataTypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableDataTypeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableDataTypeDefaultTypeInternal() {}
  union {
    SerializableDataType _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableDataTypeDefaultTypeInternal _SerializableDataType_default_instance_;
}  // namespace NES
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_SerializableDataType_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SerializableDataType_2eproto = nullptr;
const ::uint32_t
    TableStruct_SerializableDataType_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableDataType, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableDataType, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableDataType, _impl_.nullable_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NES::SerializableDataType)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NES::_SerializableDataType_default_instance_._instance,
};
const char descriptor_table_protodef_SerializableDataType_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032SerializableDataType.proto\022\003NES\"\207\002\n\024Se"
    "rializableDataType\022,\n\004type\030\001 \001(\0162\036.NES.S"
    "erializableDataType.Type\022\020\n\010nullable\030\002 \001"
    "(\010\"\256\001\n\004Type\022\t\n\005UINT8\020\000\022\n\n\006UINT16\020\001\022\n\n\006UI"
    "NT32\020\002\022\n\n\006UINT64\020\003\022\010\n\004INT8\020\004\022\t\n\005INT16\020\005\022"
    "\t\n\005INT32\020\006\022\t\n\005INT64\020\007\022\013\n\007FLOAT32\020\010\022\013\n\007FL"
    "OAT64\020\t\022\013\n\007BOOLEAN\020\n\022\010\n\004CHAR\020\013\022\r\n\tUNDEFI"
    "NED\020\014\022\014\n\010VARSIZED\020\rb\006proto3"
};
static ::absl::once_flag descriptor_table_SerializableDataType_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SerializableDataType_2eproto = {
    false,
    false,
    307,
    descriptor_table_protodef_SerializableDataType_2eproto,
    "SerializableDataType.proto",
    &descriptor_table_SerializableDataType_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SerializableDataType_2eproto::offsets,
    file_level_enum_descriptors_SerializableDataType_2eproto,
    file_level_service_descriptors_SerializableDataType_2eproto,
};
namespace NES {
const ::google::protobuf::EnumDescriptor* SerializableDataType_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_SerializableDataType_2eproto);
  return file_level_enum_descriptors_SerializableDataType_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SerializableDataType_Type_internal_data_[] = {
    917504u, 0u, };
bool SerializableDataType_Type_IsValid(int value) {
  return 0 <= value && value <= 13;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr SerializableDataType_Type SerializableDataType::UINT8;
constexpr SerializableDataType_Type SerializableDataType::UINT16;
constexpr SerializableDataType_Type SerializableDataType::UINT32;
constexpr SerializableDataType_Type SerializableDataType::UINT64;
constexpr SerializableDataType_Type SerializableDataType::INT8;
constexpr SerializableDataType_Type SerializableDataType::INT16;
constexpr SerializableDataType_Type SerializableDataType::INT32;
constexpr SerializableDataType_Type SerializableDataType::INT64;
constexpr SerializableDataType_Type SerializableDataType::FLOAT32;
constexpr SerializableDataType_Type SerializableDataType::FLOAT64;
constexpr SerializableDataType_Type SerializableDataType::BOOLEAN;
constexpr SerializableDataType_Type SerializableDataType::CHAR;
constexpr SerializableDataType_Type SerializableDataType::UNDEFINED;
constexpr SerializableDataType_Type SerializableDataType::VARSIZED;
constexpr SerializableDataType_Type SerializableDataType::Type_MIN;
constexpr SerializableDataType_Type SerializableDataType::Type_MAX;
constexpr int SerializableDataType::Type_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class SerializableDataType::_Internal {
 public:
};

SerializableDataType::SerializableDataType(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableDataType)
}
SerializableDataType::SerializableDataType(
    ::google::protobuf::Arena* arena, const SerializableDataType& from)
    : SerializableDataType(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SerializableDataType::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SerializableDataType::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, nullable_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::nullable_));
}
SerializableDataType::~SerializableDataType() {
  // @@protoc_insertion_point(destructor:NES.SerializableDataType)
  SharedDtor(*this);
}
inline void SerializableDataType::SharedDtor(MessageLite& self) {
  SerializableDataType& this_ = static_cast<SerializableDataType&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SerializableDataType::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableDataType(arena);
}
constexpr auto SerializableDataType::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SerializableDataType),
                                            alignof(SerializableDataType));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableDataType::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableDataType_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableDataType::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableDataType>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableDataType::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableDataType>(), &SerializableDataType::ByteSizeLong,
            &SerializableDataType::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_._cached_size_),
        false,
    },
    &SerializableDataType::kDescriptorMethods,
    &descriptor_table_SerializableDataType_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableDataType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SerializableDataType::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableDataType>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool nullable = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SerializableDataType, _impl_.nullable_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.nullable_)}},
    // .NES.SerializableDataType.Type type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SerializableDataType, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .NES.SerializableDataType.Type type = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // bool nullable = 2;
    {PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.nullable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SerializableDataType::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableDataType)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.nullable_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.nullable_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableDataType::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableDataType& this_ = static_cast<const SerializableDataType&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableDataType::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableDataType& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableDataType)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .NES.SerializableDataType.Type type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // bool nullable = 2;
          if (this_._internal_nullable() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_nullable(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableDataType)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableDataType::ByteSizeLong(const MessageLite& base) {
          const SerializableDataType& this_ = static_cast<const SerializableDataType&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableDataType::ByteSizeLong() const {
          const SerializableDataType& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableDataType)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .NES.SerializableDataType.Type type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // bool nullable = 2;
            if (this_._internal_nullable() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableDataType::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableDataType*>(&to_msg);
  auto& from = static_cast<const SerializableDataType&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableDataType)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_nullable() != 0) {
    _this->_impl_.nullable_ = from._impl_.nullable_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableDataType::CopyFrom(const SerializableDataType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableDataType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableDataType::InternalSwap(SerializableDataType* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.nullable_)
      + sizeof(SerializableDataType::_impl_.nullable_)
      - PROTOBUF_FIELD_OFFSET(SerializableDataType, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata SerializableDataType::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SerializableDataType_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
