// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableQueryPlan.proto
// Protobuf C++ Version: 5.29.5

#ifndef SerializableQueryPlan_2eproto_2epb_2eh
#define SerializableQueryPlan_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "SerializableQueryId.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SerializableQueryPlan_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SerializableQueryPlan_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SerializableQueryPlan_2eproto;
namespace NES {
class SerializableQueryPlan;
struct SerializableQueryPlanDefaultTypeInternal;
extern SerializableQueryPlanDefaultTypeInternal _SerializableQueryPlan_default_instance_;
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NES {

// ===================================================================


// -------------------------------------------------------------------

class SerializableQueryPlan final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableQueryPlan) */ {
 public:
  inline SerializableQueryPlan() : SerializableQueryPlan(nullptr) {}
  ~SerializableQueryPlan() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableQueryPlan* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableQueryPlan));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableQueryPlan(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableQueryPlan(const SerializableQueryPlan& from) : SerializableQueryPlan(nullptr, from) {}
  inline SerializableQueryPlan(SerializableQueryPlan&& from) noexcept
      : SerializableQueryPlan(nullptr, std::move(from)) {}
  inline SerializableQueryPlan& operator=(const SerializableQueryPlan& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableQueryPlan& operator=(SerializableQueryPlan&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableQueryPlan& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableQueryPlan* internal_default_instance() {
    return reinterpret_cast<const SerializableQueryPlan*>(
        &_SerializableQueryPlan_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SerializableQueryPlan& a, SerializableQueryPlan& b) { a.Swap(&b); }
  inline void Swap(SerializableQueryPlan* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableQueryPlan* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableQueryPlan* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableQueryPlan>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableQueryPlan& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableQueryPlan& from) { SerializableQueryPlan::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableQueryPlan* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableQueryPlan"; }

 protected:
  explicit SerializableQueryPlan(::google::protobuf::Arena* arena);
  SerializableQueryPlan(::google::protobuf::Arena* arena, const SerializableQueryPlan& from);
  SerializableQueryPlan(::google::protobuf::Arena* arena, SerializableQueryPlan&& from) noexcept
      : SerializableQueryPlan(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReflectedOperatorsFieldNumber = 1,
    kRootOperatorIdsFieldNumber = 2,
    kQueryIdFieldNumber = 3,
  };
  // repeated string reflectedOperators = 1;
  int reflectedoperators_size() const;
  private:
  int _internal_reflectedoperators_size() const;

  public:
  void clear_reflectedoperators() ;
  const std::string& reflectedoperators(int index) const;
  std::string* mutable_reflectedoperators(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_reflectedoperators(int index, Arg_&& value, Args_... args);
  std::string* add_reflectedoperators();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_reflectedoperators(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& reflectedoperators() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_reflectedoperators();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_reflectedoperators() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_reflectedoperators();

  public:
  // repeated uint64 rootOperatorIds = 2;
  int rootoperatorids_size() const;
  private:
  int _internal_rootoperatorids_size() const;

  public:
  void clear_rootoperatorids() ;
  ::uint64_t rootoperatorids(int index) const;
  void set_rootoperatorids(int index, ::uint64_t value);
  void add_rootoperatorids(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& rootoperatorids() const;
  ::google::protobuf::RepeatedField<::uint64_t>* mutable_rootoperatorids();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_rootoperatorids() const;
  ::google::protobuf::RepeatedField<::uint64_t>* _internal_mutable_rootoperatorids();

  public:
  // optional .NES.SerializableQueryId queryId = 3;
  bool has_queryid() const;
  void clear_queryid() ;
  const ::NES::SerializableQueryId& queryid() const;
  PROTOBUF_NODISCARD ::NES::SerializableQueryId* release_queryid();
  ::NES::SerializableQueryId* mutable_queryid();
  void set_allocated_queryid(::NES::SerializableQueryId* value);
  void unsafe_arena_set_allocated_queryid(::NES::SerializableQueryId* value);
  ::NES::SerializableQueryId* unsafe_arena_release_queryid();

  private:
  const ::NES::SerializableQueryId& _internal_queryid() const;
  ::NES::SerializableQueryId* _internal_mutable_queryid();

  public:
  // @@protoc_insertion_point(class_scope:NES.SerializableQueryPlan)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableQueryPlan& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> reflectedoperators_;
    ::google::protobuf::RepeatedField<::uint64_t> rootoperatorids_;
    ::google::protobuf::internal::CachedSize _rootoperatorids_cached_byte_size_;
    ::NES::SerializableQueryId* queryid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableQueryPlan_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializableQueryPlan

// repeated string reflectedOperators = 1;
inline int SerializableQueryPlan::_internal_reflectedoperators_size() const {
  return _internal_reflectedoperators().size();
}
inline int SerializableQueryPlan::reflectedoperators_size() const {
  return _internal_reflectedoperators_size();
}
inline void SerializableQueryPlan::clear_reflectedoperators() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reflectedoperators_.Clear();
}
inline std::string* SerializableQueryPlan::add_reflectedoperators() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_reflectedoperators()->Add();
  // @@protoc_insertion_point(field_add_mutable:NES.SerializableQueryPlan.reflectedOperators)
  return _s;
}
inline const std::string& SerializableQueryPlan::reflectedoperators(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableQueryPlan.reflectedOperators)
  return _internal_reflectedoperators().Get(index);
}
inline std::string* SerializableQueryPlan::mutable_reflectedoperators(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:NES.SerializableQueryPlan.reflectedOperators)
  return _internal_mutable_reflectedoperators()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SerializableQueryPlan::set_reflectedoperators(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_reflectedoperators()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:NES.SerializableQueryPlan.reflectedOperators)
}
template <typename Arg_, typename... Args_>
inline void SerializableQueryPlan::add_reflectedoperators(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_reflectedoperators(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:NES.SerializableQueryPlan.reflectedOperators)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SerializableQueryPlan::reflectedoperators() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:NES.SerializableQueryPlan.reflectedOperators)
  return _internal_reflectedoperators();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SerializableQueryPlan::mutable_reflectedoperators() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:NES.SerializableQueryPlan.reflectedOperators)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_reflectedoperators();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SerializableQueryPlan::_internal_reflectedoperators() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reflectedoperators_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SerializableQueryPlan::_internal_mutable_reflectedoperators() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.reflectedoperators_;
}

// repeated uint64 rootOperatorIds = 2;
inline int SerializableQueryPlan::_internal_rootoperatorids_size() const {
  return _internal_rootoperatorids().size();
}
inline int SerializableQueryPlan::rootoperatorids_size() const {
  return _internal_rootoperatorids_size();
}
inline void SerializableQueryPlan::clear_rootoperatorids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rootoperatorids_.Clear();
}
inline ::uint64_t SerializableQueryPlan::rootoperatorids(int index) const {
  // @@protoc_insertion_point(field_get:NES.SerializableQueryPlan.rootOperatorIds)
  return _internal_rootoperatorids().Get(index);
}
inline void SerializableQueryPlan::set_rootoperatorids(int index, ::uint64_t value) {
  _internal_mutable_rootoperatorids()->Set(index, value);
  // @@protoc_insertion_point(field_set:NES.SerializableQueryPlan.rootOperatorIds)
}
inline void SerializableQueryPlan::add_rootoperatorids(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rootoperatorids()->Add(value);
  // @@protoc_insertion_point(field_add:NES.SerializableQueryPlan.rootOperatorIds)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& SerializableQueryPlan::rootoperatorids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:NES.SerializableQueryPlan.rootOperatorIds)
  return _internal_rootoperatorids();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* SerializableQueryPlan::mutable_rootoperatorids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:NES.SerializableQueryPlan.rootOperatorIds)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rootoperatorids();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
SerializableQueryPlan::_internal_rootoperatorids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rootoperatorids_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* SerializableQueryPlan::_internal_mutable_rootoperatorids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rootoperatorids_;
}

// optional .NES.SerializableQueryId queryId = 3;
inline bool SerializableQueryPlan::has_queryid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.queryid_ != nullptr);
  return value;
}
inline const ::NES::SerializableQueryId& SerializableQueryPlan::_internal_queryid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::NES::SerializableQueryId* p = _impl_.queryid_;
  return p != nullptr ? *p : reinterpret_cast<const ::NES::SerializableQueryId&>(::NES::_SerializableQueryId_default_instance_);
}
inline const ::NES::SerializableQueryId& SerializableQueryPlan::queryid() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableQueryPlan.queryId)
  return _internal_queryid();
}
inline void SerializableQueryPlan::unsafe_arena_set_allocated_queryid(::NES::SerializableQueryId* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.queryid_);
  }
  _impl_.queryid_ = reinterpret_cast<::NES::SerializableQueryId*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NES.SerializableQueryPlan.queryId)
}
inline ::NES::SerializableQueryId* SerializableQueryPlan::release_queryid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::NES::SerializableQueryId* released = _impl_.queryid_;
  _impl_.queryid_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::NES::SerializableQueryId* SerializableQueryPlan::unsafe_arena_release_queryid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableQueryPlan.queryId)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::NES::SerializableQueryId* temp = _impl_.queryid_;
  _impl_.queryid_ = nullptr;
  return temp;
}
inline ::NES::SerializableQueryId* SerializableQueryPlan::_internal_mutable_queryid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.queryid_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::NES::SerializableQueryId>(GetArena());
    _impl_.queryid_ = reinterpret_cast<::NES::SerializableQueryId*>(p);
  }
  return _impl_.queryid_;
}
inline ::NES::SerializableQueryId* SerializableQueryPlan::mutable_queryid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::NES::SerializableQueryId* _msg = _internal_mutable_queryid();
  // @@protoc_insertion_point(field_mutable:NES.SerializableQueryPlan.queryId)
  return _msg;
}
inline void SerializableQueryPlan::set_allocated_queryid(::NES::SerializableQueryId* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.queryid_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.queryid_ = reinterpret_cast<::NES::SerializableQueryId*>(value);
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableQueryPlan.queryId)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NES


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SerializableQueryPlan_2eproto_2epb_2eh
