// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableIdentifier.proto
// Protobuf C++ Version: 5.29.5

#ifndef SerializableIdentifier_2eproto_2epb_2eh
#define SerializableIdentifier_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SerializableIdentifier_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SerializableIdentifier_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SerializableIdentifier_2eproto;
namespace NES {
class SerializableIdentifier;
struct SerializableIdentifierDefaultTypeInternal;
extern SerializableIdentifierDefaultTypeInternal _SerializableIdentifier_default_instance_;
class SerializableIdentifierList;
struct SerializableIdentifierListDefaultTypeInternal;
extern SerializableIdentifierListDefaultTypeInternal _SerializableIdentifierList_default_instance_;
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NES {

// ===================================================================


// -------------------------------------------------------------------

class SerializableIdentifier final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableIdentifier) */ {
 public:
  inline SerializableIdentifier() : SerializableIdentifier(nullptr) {}
  ~SerializableIdentifier() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableIdentifier* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableIdentifier));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableIdentifier(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableIdentifier(const SerializableIdentifier& from) : SerializableIdentifier(nullptr, from) {}
  inline SerializableIdentifier(SerializableIdentifier&& from) noexcept
      : SerializableIdentifier(nullptr, std::move(from)) {}
  inline SerializableIdentifier& operator=(const SerializableIdentifier& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableIdentifier& operator=(SerializableIdentifier&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableIdentifier& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableIdentifier* internal_default_instance() {
    return reinterpret_cast<const SerializableIdentifier*>(
        &_SerializableIdentifier_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SerializableIdentifier& a, SerializableIdentifier& b) { a.Swap(&b); }
  inline void Swap(SerializableIdentifier* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableIdentifier* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableIdentifier* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableIdentifier>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableIdentifier& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableIdentifier& from) { SerializableIdentifier::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableIdentifier* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableIdentifier"; }

 protected:
  explicit SerializableIdentifier(::google::protobuf::Arena* arena);
  SerializableIdentifier(::google::protobuf::Arena* arena, const SerializableIdentifier& from);
  SerializableIdentifier(::google::protobuf::Arena* arena, SerializableIdentifier&& from) noexcept
      : SerializableIdentifier(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
    kCaseSensitiveFieldNumber = 2,
  };
  // string value = 1;
  void clear_value() ;
  const std::string& value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // bool caseSensitive = 2;
  void clear_casesensitive() ;
  bool casesensitive() const;
  void set_casesensitive(bool value);

  private:
  bool _internal_casesensitive() const;
  void _internal_set_casesensitive(bool value);

  public:
  // @@protoc_insertion_point(class_scope:NES.SerializableIdentifier)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      40, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableIdentifier& from_msg);
    ::google::protobuf::internal::ArenaStringPtr value_;
    bool casesensitive_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableIdentifier_2eproto;
};
// -------------------------------------------------------------------

class SerializableIdentifierList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableIdentifierList) */ {
 public:
  inline SerializableIdentifierList() : SerializableIdentifierList(nullptr) {}
  ~SerializableIdentifierList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableIdentifierList* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableIdentifierList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableIdentifierList(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableIdentifierList(const SerializableIdentifierList& from) : SerializableIdentifierList(nullptr, from) {}
  inline SerializableIdentifierList(SerializableIdentifierList&& from) noexcept
      : SerializableIdentifierList(nullptr, std::move(from)) {}
  inline SerializableIdentifierList& operator=(const SerializableIdentifierList& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableIdentifierList& operator=(SerializableIdentifierList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableIdentifierList& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableIdentifierList* internal_default_instance() {
    return reinterpret_cast<const SerializableIdentifierList*>(
        &_SerializableIdentifierList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SerializableIdentifierList& a, SerializableIdentifierList& b) { a.Swap(&b); }
  inline void Swap(SerializableIdentifierList* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableIdentifierList* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableIdentifierList* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableIdentifierList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableIdentifierList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableIdentifierList& from) { SerializableIdentifierList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableIdentifierList* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableIdentifierList"; }

 protected:
  explicit SerializableIdentifierList(::google::protobuf::Arena* arena);
  SerializableIdentifierList(::google::protobuf::Arena* arena, const SerializableIdentifierList& from);
  SerializableIdentifierList(::google::protobuf::Arena* arena, SerializableIdentifierList&& from) noexcept
      : SerializableIdentifierList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdentifiersFieldNumber = 1,
  };
  // repeated .NES.SerializableIdentifier identifiers = 1;
  int identifiers_size() const;
  private:
  int _internal_identifiers_size() const;

  public:
  void clear_identifiers() ;
  ::NES::SerializableIdentifier* mutable_identifiers(int index);
  ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>* mutable_identifiers();

  private:
  const ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>& _internal_identifiers() const;
  ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>* _internal_mutable_identifiers();
  public:
  const ::NES::SerializableIdentifier& identifiers(int index) const;
  ::NES::SerializableIdentifier* add_identifiers();
  const ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>& identifiers() const;
  // @@protoc_insertion_point(class_scope:NES.SerializableIdentifierList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableIdentifierList& from_msg);
    ::google::protobuf::RepeatedPtrField< ::NES::SerializableIdentifier > identifiers_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableIdentifier_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializableIdentifier

// string value = 1;
inline void SerializableIdentifier::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
}
inline const std::string& SerializableIdentifier::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableIdentifier.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SerializableIdentifier::set_value(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NES.SerializableIdentifier.value)
}
inline std::string* SerializableIdentifier::mutable_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:NES.SerializableIdentifier.value)
  return _s;
}
inline const std::string& SerializableIdentifier::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void SerializableIdentifier::_internal_set_value(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline std::string* SerializableIdentifier::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline std::string* SerializableIdentifier::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableIdentifier.value)
  return _impl_.value_.Release();
}
inline void SerializableIdentifier::set_allocated_value(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableIdentifier.value)
}

// bool caseSensitive = 2;
inline void SerializableIdentifier::clear_casesensitive() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.casesensitive_ = false;
}
inline bool SerializableIdentifier::casesensitive() const {
  // @@protoc_insertion_point(field_get:NES.SerializableIdentifier.caseSensitive)
  return _internal_casesensitive();
}
inline void SerializableIdentifier::set_casesensitive(bool value) {
  _internal_set_casesensitive(value);
  // @@protoc_insertion_point(field_set:NES.SerializableIdentifier.caseSensitive)
}
inline bool SerializableIdentifier::_internal_casesensitive() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.casesensitive_;
}
inline void SerializableIdentifier::_internal_set_casesensitive(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.casesensitive_ = value;
}

// -------------------------------------------------------------------

// SerializableIdentifierList

// repeated .NES.SerializableIdentifier identifiers = 1;
inline int SerializableIdentifierList::_internal_identifiers_size() const {
  return _internal_identifiers().size();
}
inline int SerializableIdentifierList::identifiers_size() const {
  return _internal_identifiers_size();
}
inline void SerializableIdentifierList::clear_identifiers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifiers_.Clear();
}
inline ::NES::SerializableIdentifier* SerializableIdentifierList::mutable_identifiers(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:NES.SerializableIdentifierList.identifiers)
  return _internal_mutable_identifiers()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>* SerializableIdentifierList::mutable_identifiers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:NES.SerializableIdentifierList.identifiers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_identifiers();
}
inline const ::NES::SerializableIdentifier& SerializableIdentifierList::identifiers(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableIdentifierList.identifiers)
  return _internal_identifiers().Get(index);
}
inline ::NES::SerializableIdentifier* SerializableIdentifierList::add_identifiers() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::NES::SerializableIdentifier* _add = _internal_mutable_identifiers()->Add();
  // @@protoc_insertion_point(field_add:NES.SerializableIdentifierList.identifiers)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>& SerializableIdentifierList::identifiers() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:NES.SerializableIdentifierList.identifiers)
  return _internal_identifiers();
}
inline const ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>&
SerializableIdentifierList::_internal_identifiers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identifiers_;
}
inline ::google::protobuf::RepeatedPtrField<::NES::SerializableIdentifier>*
SerializableIdentifierList::_internal_mutable_identifiers() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.identifiers_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NES


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SerializableIdentifier_2eproto_2epb_2eh
