// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableVariantDescriptor.proto
// Protobuf C++ Version: 5.29.5

#ifndef SerializableVariantDescriptor_2eproto_2epb_2eh
#define SerializableVariantDescriptor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SerializableVariantDescriptor_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SerializableVariantDescriptor_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SerializableVariantDescriptor_2eproto;
namespace NES {
class SerializableEnumWrapper;
struct SerializableEnumWrapperDefaultTypeInternal;
extern SerializableEnumWrapperDefaultTypeInternal _SerializableEnumWrapper_default_instance_;
class SerializableVariantDescriptor;
struct SerializableVariantDescriptorDefaultTypeInternal;
extern SerializableVariantDescriptorDefaultTypeInternal _SerializableVariantDescriptor_default_instance_;
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NES {

// ===================================================================


// -------------------------------------------------------------------

class SerializableEnumWrapper final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableEnumWrapper) */ {
 public:
  inline SerializableEnumWrapper() : SerializableEnumWrapper(nullptr) {}
  ~SerializableEnumWrapper() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableEnumWrapper* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableEnumWrapper));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableEnumWrapper(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableEnumWrapper(const SerializableEnumWrapper& from) : SerializableEnumWrapper(nullptr, from) {}
  inline SerializableEnumWrapper(SerializableEnumWrapper&& from) noexcept
      : SerializableEnumWrapper(nullptr, std::move(from)) {}
  inline SerializableEnumWrapper& operator=(const SerializableEnumWrapper& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableEnumWrapper& operator=(SerializableEnumWrapper&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableEnumWrapper& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableEnumWrapper* internal_default_instance() {
    return reinterpret_cast<const SerializableEnumWrapper*>(
        &_SerializableEnumWrapper_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SerializableEnumWrapper& a, SerializableEnumWrapper& b) { a.Swap(&b); }
  inline void Swap(SerializableEnumWrapper* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableEnumWrapper* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableEnumWrapper* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableEnumWrapper>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableEnumWrapper& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableEnumWrapper& from) { SerializableEnumWrapper::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableEnumWrapper* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableEnumWrapper"; }

 protected:
  explicit SerializableEnumWrapper(::google::protobuf::Arena* arena);
  SerializableEnumWrapper(::google::protobuf::Arena* arena, const SerializableEnumWrapper& from);
  SerializableEnumWrapper(::google::protobuf::Arena* arena, SerializableEnumWrapper&& from) noexcept
      : SerializableEnumWrapper(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
  };
  // string value = 1;
  void clear_value() ;
  const std::string& value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:NES.SerializableEnumWrapper)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableEnumWrapper& from_msg);
    ::google::protobuf::internal::ArenaStringPtr value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableVariantDescriptor_2eproto;
};
// -------------------------------------------------------------------

class SerializableVariantDescriptor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableVariantDescriptor) */ {
 public:
  inline SerializableVariantDescriptor() : SerializableVariantDescriptor(nullptr) {}
  ~SerializableVariantDescriptor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableVariantDescriptor* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableVariantDescriptor));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableVariantDescriptor(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableVariantDescriptor(const SerializableVariantDescriptor& from) : SerializableVariantDescriptor(nullptr, from) {}
  inline SerializableVariantDescriptor(SerializableVariantDescriptor&& from) noexcept
      : SerializableVariantDescriptor(nullptr, std::move(from)) {}
  inline SerializableVariantDescriptor& operator=(const SerializableVariantDescriptor& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableVariantDescriptor& operator=(SerializableVariantDescriptor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableVariantDescriptor& default_instance() {
    return *internal_default_instance();
  }
  enum ValueCase {
    kIntValue = 1,
    kUintValue = 2,
    kLongValue = 3,
    kUlongValue = 4,
    kBoolValue = 5,
    kCharValue = 6,
    kFloatValue = 7,
    kDoubleValue = 8,
    kStringValue = 9,
    kEnumValue = 10,
    VALUE_NOT_SET = 0,
  };
  static inline const SerializableVariantDescriptor* internal_default_instance() {
    return reinterpret_cast<const SerializableVariantDescriptor*>(
        &_SerializableVariantDescriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SerializableVariantDescriptor& a, SerializableVariantDescriptor& b) { a.Swap(&b); }
  inline void Swap(SerializableVariantDescriptor* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableVariantDescriptor* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableVariantDescriptor* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableVariantDescriptor>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableVariantDescriptor& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableVariantDescriptor& from) { SerializableVariantDescriptor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableVariantDescriptor* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableVariantDescriptor"; }

 protected:
  explicit SerializableVariantDescriptor(::google::protobuf::Arena* arena);
  SerializableVariantDescriptor(::google::protobuf::Arena* arena, const SerializableVariantDescriptor& from);
  SerializableVariantDescriptor(::google::protobuf::Arena* arena, SerializableVariantDescriptor&& from) noexcept
      : SerializableVariantDescriptor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIntValueFieldNumber = 1,
    kUintValueFieldNumber = 2,
    kLongValueFieldNumber = 3,
    kUlongValueFieldNumber = 4,
    kBoolValueFieldNumber = 5,
    kCharValueFieldNumber = 6,
    kFloatValueFieldNumber = 7,
    kDoubleValueFieldNumber = 8,
    kStringValueFieldNumber = 9,
    kEnumValueFieldNumber = 10,
  };
  // int32 int_value = 1;
  bool has_int_value() const;
  void clear_int_value() ;
  ::int32_t int_value() const;
  void set_int_value(::int32_t value);

  private:
  ::int32_t _internal_int_value() const;
  void _internal_set_int_value(::int32_t value);

  public:
  // uint32 uint_value = 2;
  bool has_uint_value() const;
  void clear_uint_value() ;
  ::uint32_t uint_value() const;
  void set_uint_value(::uint32_t value);

  private:
  ::uint32_t _internal_uint_value() const;
  void _internal_set_uint_value(::uint32_t value);

  public:
  // int64 long_value = 3;
  bool has_long_value() const;
  void clear_long_value() ;
  ::int64_t long_value() const;
  void set_long_value(::int64_t value);

  private:
  ::int64_t _internal_long_value() const;
  void _internal_set_long_value(::int64_t value);

  public:
  // uint64 ulong_value = 4;
  bool has_ulong_value() const;
  void clear_ulong_value() ;
  ::uint64_t ulong_value() const;
  void set_ulong_value(::uint64_t value);

  private:
  ::uint64_t _internal_ulong_value() const;
  void _internal_set_ulong_value(::uint64_t value);

  public:
  // bool bool_value = 5;
  bool has_bool_value() const;
  void clear_bool_value() ;
  bool bool_value() const;
  void set_bool_value(bool value);

  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);

  public:
  // fixed32 char_value = 6;
  bool has_char_value() const;
  void clear_char_value() ;
  ::uint32_t char_value() const;
  void set_char_value(::uint32_t value);

  private:
  ::uint32_t _internal_char_value() const;
  void _internal_set_char_value(::uint32_t value);

  public:
  // float float_value = 7;
  bool has_float_value() const;
  void clear_float_value() ;
  float float_value() const;
  void set_float_value(float value);

  private:
  float _internal_float_value() const;
  void _internal_set_float_value(float value);

  public:
  // double double_value = 8;
  bool has_double_value() const;
  void clear_double_value() ;
  double double_value() const;
  void set_double_value(double value);

  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);

  public:
  // string string_value = 9;
  bool has_string_value() const;
  void clear_string_value() ;
  const std::string& string_value() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_string_value(Arg_&& arg, Args_... args);
  std::string* mutable_string_value();
  PROTOBUF_NODISCARD std::string* release_string_value();
  void set_allocated_string_value(std::string* value);

  private:
  const std::string& _internal_string_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_value(
      const std::string& value);
  std::string* _internal_mutable_string_value();

  public:
  // .NES.SerializableEnumWrapper enum_value = 10;
  bool has_enum_value() const;
  private:
  bool _internal_has_enum_value() const;

  public:
  void clear_enum_value() ;
  const ::NES::SerializableEnumWrapper& enum_value() const;
  PROTOBUF_NODISCARD ::NES::SerializableEnumWrapper* release_enum_value();
  ::NES::SerializableEnumWrapper* mutable_enum_value();
  void set_allocated_enum_value(::NES::SerializableEnumWrapper* value);
  void unsafe_arena_set_allocated_enum_value(::NES::SerializableEnumWrapper* value);
  ::NES::SerializableEnumWrapper* unsafe_arena_release_enum_value();

  private:
  const ::NES::SerializableEnumWrapper& _internal_enum_value() const;
  ::NES::SerializableEnumWrapper* _internal_mutable_enum_value();

  public:
  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:NES.SerializableVariantDescriptor)
 private:
  class _Internal;
  void set_has_int_value();
  void set_has_uint_value();
  void set_has_long_value();
  void set_has_ulong_value();
  void set_has_bool_value();
  void set_has_char_value();
  void set_has_float_value();
  void set_has_double_value();
  void set_has_string_value();
  void set_has_enum_value();
  inline bool has_value() const;
  inline void clear_has_value();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 10, 1,
      62, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableVariantDescriptor& from_msg);
    union ValueUnion {
      constexpr ValueUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::int32_t int_value_;
      ::uint32_t uint_value_;
      ::int64_t long_value_;
      ::uint64_t ulong_value_;
      bool bool_value_;
      ::uint32_t char_value_;
      float float_value_;
      double double_value_;
      ::google::protobuf::internal::ArenaStringPtr string_value_;
      ::NES::SerializableEnumWrapper* enum_value_;
    } value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableVariantDescriptor_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializableEnumWrapper

// string value = 1;
inline void SerializableEnumWrapper::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
}
inline const std::string& SerializableEnumWrapper::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableEnumWrapper.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SerializableEnumWrapper::set_value(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NES.SerializableEnumWrapper.value)
}
inline std::string* SerializableEnumWrapper::mutable_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:NES.SerializableEnumWrapper.value)
  return _s;
}
inline const std::string& SerializableEnumWrapper::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void SerializableEnumWrapper::_internal_set_value(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline std::string* SerializableEnumWrapper::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline std::string* SerializableEnumWrapper::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableEnumWrapper.value)
  return _impl_.value_.Release();
}
inline void SerializableEnumWrapper::set_allocated_value(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableEnumWrapper.value)
}

// -------------------------------------------------------------------

// SerializableVariantDescriptor

// int32 int_value = 1;
inline bool SerializableVariantDescriptor::has_int_value() const {
  return value_case() == kIntValue;
}
inline void SerializableVariantDescriptor::set_has_int_value() {
  _impl_._oneof_case_[0] = kIntValue;
}
inline void SerializableVariantDescriptor::clear_int_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kIntValue) {
    _impl_.value_.int_value_ = 0;
    clear_has_value();
  }
}
inline ::int32_t SerializableVariantDescriptor::int_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.int_value)
  return _internal_int_value();
}
inline void SerializableVariantDescriptor::set_int_value(::int32_t value) {
  if (value_case() != kIntValue) {
    clear_value();
    set_has_int_value();
  }
  _impl_.value_.int_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.int_value)
}
inline ::int32_t SerializableVariantDescriptor::_internal_int_value() const {
  if (value_case() == kIntValue) {
    return _impl_.value_.int_value_;
  }
  return 0;
}

// uint32 uint_value = 2;
inline bool SerializableVariantDescriptor::has_uint_value() const {
  return value_case() == kUintValue;
}
inline void SerializableVariantDescriptor::set_has_uint_value() {
  _impl_._oneof_case_[0] = kUintValue;
}
inline void SerializableVariantDescriptor::clear_uint_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kUintValue) {
    _impl_.value_.uint_value_ = 0u;
    clear_has_value();
  }
}
inline ::uint32_t SerializableVariantDescriptor::uint_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.uint_value)
  return _internal_uint_value();
}
inline void SerializableVariantDescriptor::set_uint_value(::uint32_t value) {
  if (value_case() != kUintValue) {
    clear_value();
    set_has_uint_value();
  }
  _impl_.value_.uint_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.uint_value)
}
inline ::uint32_t SerializableVariantDescriptor::_internal_uint_value() const {
  if (value_case() == kUintValue) {
    return _impl_.value_.uint_value_;
  }
  return 0u;
}

// int64 long_value = 3;
inline bool SerializableVariantDescriptor::has_long_value() const {
  return value_case() == kLongValue;
}
inline void SerializableVariantDescriptor::set_has_long_value() {
  _impl_._oneof_case_[0] = kLongValue;
}
inline void SerializableVariantDescriptor::clear_long_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kLongValue) {
    _impl_.value_.long_value_ = ::int64_t{0};
    clear_has_value();
  }
}
inline ::int64_t SerializableVariantDescriptor::long_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.long_value)
  return _internal_long_value();
}
inline void SerializableVariantDescriptor::set_long_value(::int64_t value) {
  if (value_case() != kLongValue) {
    clear_value();
    set_has_long_value();
  }
  _impl_.value_.long_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.long_value)
}
inline ::int64_t SerializableVariantDescriptor::_internal_long_value() const {
  if (value_case() == kLongValue) {
    return _impl_.value_.long_value_;
  }
  return ::int64_t{0};
}

// uint64 ulong_value = 4;
inline bool SerializableVariantDescriptor::has_ulong_value() const {
  return value_case() == kUlongValue;
}
inline void SerializableVariantDescriptor::set_has_ulong_value() {
  _impl_._oneof_case_[0] = kUlongValue;
}
inline void SerializableVariantDescriptor::clear_ulong_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kUlongValue) {
    _impl_.value_.ulong_value_ = ::uint64_t{0u};
    clear_has_value();
  }
}
inline ::uint64_t SerializableVariantDescriptor::ulong_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.ulong_value)
  return _internal_ulong_value();
}
inline void SerializableVariantDescriptor::set_ulong_value(::uint64_t value) {
  if (value_case() != kUlongValue) {
    clear_value();
    set_has_ulong_value();
  }
  _impl_.value_.ulong_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.ulong_value)
}
inline ::uint64_t SerializableVariantDescriptor::_internal_ulong_value() const {
  if (value_case() == kUlongValue) {
    return _impl_.value_.ulong_value_;
  }
  return ::uint64_t{0u};
}

// bool bool_value = 5;
inline bool SerializableVariantDescriptor::has_bool_value() const {
  return value_case() == kBoolValue;
}
inline void SerializableVariantDescriptor::set_has_bool_value() {
  _impl_._oneof_case_[0] = kBoolValue;
}
inline void SerializableVariantDescriptor::clear_bool_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kBoolValue) {
    _impl_.value_.bool_value_ = false;
    clear_has_value();
  }
}
inline bool SerializableVariantDescriptor::bool_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.bool_value)
  return _internal_bool_value();
}
inline void SerializableVariantDescriptor::set_bool_value(bool value) {
  if (value_case() != kBoolValue) {
    clear_value();
    set_has_bool_value();
  }
  _impl_.value_.bool_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.bool_value)
}
inline bool SerializableVariantDescriptor::_internal_bool_value() const {
  if (value_case() == kBoolValue) {
    return _impl_.value_.bool_value_;
  }
  return false;
}

// fixed32 char_value = 6;
inline bool SerializableVariantDescriptor::has_char_value() const {
  return value_case() == kCharValue;
}
inline void SerializableVariantDescriptor::set_has_char_value() {
  _impl_._oneof_case_[0] = kCharValue;
}
inline void SerializableVariantDescriptor::clear_char_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kCharValue) {
    _impl_.value_.char_value_ = 0u;
    clear_has_value();
  }
}
inline ::uint32_t SerializableVariantDescriptor::char_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.char_value)
  return _internal_char_value();
}
inline void SerializableVariantDescriptor::set_char_value(::uint32_t value) {
  if (value_case() != kCharValue) {
    clear_value();
    set_has_char_value();
  }
  _impl_.value_.char_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.char_value)
}
inline ::uint32_t SerializableVariantDescriptor::_internal_char_value() const {
  if (value_case() == kCharValue) {
    return _impl_.value_.char_value_;
  }
  return 0u;
}

// float float_value = 7;
inline bool SerializableVariantDescriptor::has_float_value() const {
  return value_case() == kFloatValue;
}
inline void SerializableVariantDescriptor::set_has_float_value() {
  _impl_._oneof_case_[0] = kFloatValue;
}
inline void SerializableVariantDescriptor::clear_float_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kFloatValue) {
    _impl_.value_.float_value_ = 0;
    clear_has_value();
  }
}
inline float SerializableVariantDescriptor::float_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.float_value)
  return _internal_float_value();
}
inline void SerializableVariantDescriptor::set_float_value(float value) {
  if (value_case() != kFloatValue) {
    clear_value();
    set_has_float_value();
  }
  _impl_.value_.float_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.float_value)
}
inline float SerializableVariantDescriptor::_internal_float_value() const {
  if (value_case() == kFloatValue) {
    return _impl_.value_.float_value_;
  }
  return 0;
}

// double double_value = 8;
inline bool SerializableVariantDescriptor::has_double_value() const {
  return value_case() == kDoubleValue;
}
inline void SerializableVariantDescriptor::set_has_double_value() {
  _impl_._oneof_case_[0] = kDoubleValue;
}
inline void SerializableVariantDescriptor::clear_double_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kDoubleValue) {
    _impl_.value_.double_value_ = 0;
    clear_has_value();
  }
}
inline double SerializableVariantDescriptor::double_value() const {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.double_value)
  return _internal_double_value();
}
inline void SerializableVariantDescriptor::set_double_value(double value) {
  if (value_case() != kDoubleValue) {
    clear_value();
    set_has_double_value();
  }
  _impl_.value_.double_value_ = value;
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.double_value)
}
inline double SerializableVariantDescriptor::_internal_double_value() const {
  if (value_case() == kDoubleValue) {
    return _impl_.value_.double_value_;
  }
  return 0;
}

// string string_value = 9;
inline bool SerializableVariantDescriptor::has_string_value() const {
  return value_case() == kStringValue;
}
inline void SerializableVariantDescriptor::set_has_string_value() {
  _impl_._oneof_case_[0] = kStringValue;
}
inline void SerializableVariantDescriptor::clear_string_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kStringValue) {
    _impl_.value_.string_value_.Destroy();
    clear_has_value();
  }
}
inline const std::string& SerializableVariantDescriptor::string_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.string_value)
  return _internal_string_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SerializableVariantDescriptor::set_string_value(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() != kStringValue) {
    clear_value();

    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:NES.SerializableVariantDescriptor.string_value)
}
inline std::string* SerializableVariantDescriptor::mutable_string_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_string_value();
  // @@protoc_insertion_point(field_mutable:NES.SerializableVariantDescriptor.string_value)
  return _s;
}
inline const std::string& SerializableVariantDescriptor::_internal_string_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (value_case() != kStringValue) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.value_.string_value_.Get();
}
inline void SerializableVariantDescriptor::_internal_set_string_value(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() != kStringValue) {
    clear_value();

    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set(value, GetArena());
}
inline std::string* SerializableVariantDescriptor::_internal_mutable_string_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() != kStringValue) {
    clear_value();

    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  return _impl_.value_.string_value_.Mutable( GetArena());
}
inline std::string* SerializableVariantDescriptor::release_string_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:NES.SerializableVariantDescriptor.string_value)
  if (value_case() != kStringValue) {
    return nullptr;
  }
  clear_has_value();
  return _impl_.value_.string_value_.Release();
}
inline void SerializableVariantDescriptor::set_allocated_string_value(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_value()) {
    clear_value();
  }
  if (value != nullptr) {
    set_has_string_value();
    _impl_.value_.string_value_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableVariantDescriptor.string_value)
}

// .NES.SerializableEnumWrapper enum_value = 10;
inline bool SerializableVariantDescriptor::has_enum_value() const {
  return value_case() == kEnumValue;
}
inline bool SerializableVariantDescriptor::_internal_has_enum_value() const {
  return value_case() == kEnumValue;
}
inline void SerializableVariantDescriptor::set_has_enum_value() {
  _impl_._oneof_case_[0] = kEnumValue;
}
inline void SerializableVariantDescriptor::clear_enum_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kEnumValue) {
    if (GetArena() == nullptr) {
      delete _impl_.value_.enum_value_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.enum_value_);
    }
    clear_has_value();
  }
}
inline ::NES::SerializableEnumWrapper* SerializableVariantDescriptor::release_enum_value() {
  // @@protoc_insertion_point(field_release:NES.SerializableVariantDescriptor.enum_value)
  if (value_case() == kEnumValue) {
    clear_has_value();
    auto* temp = _impl_.value_.enum_value_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.value_.enum_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NES::SerializableEnumWrapper& SerializableVariantDescriptor::_internal_enum_value() const {
  return value_case() == kEnumValue ? *_impl_.value_.enum_value_ : reinterpret_cast<::NES::SerializableEnumWrapper&>(::NES::_SerializableEnumWrapper_default_instance_);
}
inline const ::NES::SerializableEnumWrapper& SerializableVariantDescriptor::enum_value() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:NES.SerializableVariantDescriptor.enum_value)
  return _internal_enum_value();
}
inline ::NES::SerializableEnumWrapper* SerializableVariantDescriptor::unsafe_arena_release_enum_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:NES.SerializableVariantDescriptor.enum_value)
  if (value_case() == kEnumValue) {
    clear_has_value();
    auto* temp = _impl_.value_.enum_value_;
    _impl_.value_.enum_value_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SerializableVariantDescriptor::unsafe_arena_set_allocated_enum_value(::NES::SerializableEnumWrapper* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_value();
  if (value) {
    set_has_enum_value();
    _impl_.value_.enum_value_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:NES.SerializableVariantDescriptor.enum_value)
}
inline ::NES::SerializableEnumWrapper* SerializableVariantDescriptor::_internal_mutable_enum_value() {
  if (value_case() != kEnumValue) {
    clear_value();
    set_has_enum_value();
    _impl_.value_.enum_value_ =
        ::google::protobuf::Message::DefaultConstruct<::NES::SerializableEnumWrapper>(GetArena());
  }
  return _impl_.value_.enum_value_;
}
inline ::NES::SerializableEnumWrapper* SerializableVariantDescriptor::mutable_enum_value() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::NES::SerializableEnumWrapper* _msg = _internal_mutable_enum_value();
  // @@protoc_insertion_point(field_mutable:NES.SerializableVariantDescriptor.enum_value)
  return _msg;
}

inline bool SerializableVariantDescriptor::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void SerializableVariantDescriptor::clear_has_value() {
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}
inline SerializableVariantDescriptor::ValueCase SerializableVariantDescriptor::value_case() const {
  return SerializableVariantDescriptor::ValueCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NES


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SerializableVariantDescriptor_2eproto_2epb_2eh
