// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableDataType.proto
// Protobuf C++ Version: 5.29.5

#ifndef SerializableDataType_2eproto_2epb_2eh
#define SerializableDataType_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SerializableDataType_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SerializableDataType_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_SerializableDataType_2eproto;
namespace NES {
class SerializableDataType;
struct SerializableDataTypeDefaultTypeInternal;
extern SerializableDataTypeDefaultTypeInternal _SerializableDataType_default_instance_;
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace NES {
enum SerializableDataType_Type : int {
  SerializableDataType_Type_UINT8 = 0,
  SerializableDataType_Type_UINT16 = 1,
  SerializableDataType_Type_UINT32 = 2,
  SerializableDataType_Type_UINT64 = 3,
  SerializableDataType_Type_INT8 = 4,
  SerializableDataType_Type_INT16 = 5,
  SerializableDataType_Type_INT32 = 6,
  SerializableDataType_Type_INT64 = 7,
  SerializableDataType_Type_FLOAT32 = 8,
  SerializableDataType_Type_FLOAT64 = 9,
  SerializableDataType_Type_BOOLEAN = 10,
  SerializableDataType_Type_CHAR = 11,
  SerializableDataType_Type_UNDEFINED = 12,
  SerializableDataType_Type_VARSIZED = 13,
  SerializableDataType_Type_SerializableDataType_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  SerializableDataType_Type_SerializableDataType_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool SerializableDataType_Type_IsValid(int value);
extern const uint32_t SerializableDataType_Type_internal_data_[];
constexpr SerializableDataType_Type SerializableDataType_Type_Type_MIN = static_cast<SerializableDataType_Type>(0);
constexpr SerializableDataType_Type SerializableDataType_Type_Type_MAX = static_cast<SerializableDataType_Type>(13);
constexpr int SerializableDataType_Type_Type_ARRAYSIZE = 13 + 1;
const ::google::protobuf::EnumDescriptor*
SerializableDataType_Type_descriptor();
template <typename T>
const std::string& SerializableDataType_Type_Name(T value) {
  static_assert(std::is_same<T, SerializableDataType_Type>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return SerializableDataType_Type_Name(static_cast<SerializableDataType_Type>(value));
}
template <>
inline const std::string& SerializableDataType_Type_Name(SerializableDataType_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SerializableDataType_Type_descriptor,
                                                 0, 13>(
      static_cast<int>(value));
}
inline bool SerializableDataType_Type_Parse(absl::string_view name, SerializableDataType_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SerializableDataType_Type>(
      SerializableDataType_Type_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class SerializableDataType final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NES.SerializableDataType) */ {
 public:
  inline SerializableDataType() : SerializableDataType(nullptr) {}
  ~SerializableDataType() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SerializableDataType* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SerializableDataType));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SerializableDataType(
      ::google::protobuf::internal::ConstantInitialized);

  inline SerializableDataType(const SerializableDataType& from) : SerializableDataType(nullptr, from) {}
  inline SerializableDataType(SerializableDataType&& from) noexcept
      : SerializableDataType(nullptr, std::move(from)) {}
  inline SerializableDataType& operator=(const SerializableDataType& from) {
    CopyFrom(from);
    return *this;
  }
  inline SerializableDataType& operator=(SerializableDataType&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SerializableDataType& default_instance() {
    return *internal_default_instance();
  }
  static inline const SerializableDataType* internal_default_instance() {
    return reinterpret_cast<const SerializableDataType*>(
        &_SerializableDataType_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SerializableDataType& a, SerializableDataType& b) { a.Swap(&b); }
  inline void Swap(SerializableDataType* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SerializableDataType* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SerializableDataType* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SerializableDataType>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SerializableDataType& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SerializableDataType& from) { SerializableDataType::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SerializableDataType* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NES.SerializableDataType"; }

 protected:
  explicit SerializableDataType(::google::protobuf::Arena* arena);
  SerializableDataType(::google::protobuf::Arena* arena, const SerializableDataType& from);
  SerializableDataType(::google::protobuf::Arena* arena, SerializableDataType&& from) noexcept
      : SerializableDataType(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = SerializableDataType_Type;
  static constexpr Type UINT8 = SerializableDataType_Type_UINT8;
  static constexpr Type UINT16 = SerializableDataType_Type_UINT16;
  static constexpr Type UINT32 = SerializableDataType_Type_UINT32;
  static constexpr Type UINT64 = SerializableDataType_Type_UINT64;
  static constexpr Type INT8 = SerializableDataType_Type_INT8;
  static constexpr Type INT16 = SerializableDataType_Type_INT16;
  static constexpr Type INT32 = SerializableDataType_Type_INT32;
  static constexpr Type INT64 = SerializableDataType_Type_INT64;
  static constexpr Type FLOAT32 = SerializableDataType_Type_FLOAT32;
  static constexpr Type FLOAT64 = SerializableDataType_Type_FLOAT64;
  static constexpr Type BOOLEAN = SerializableDataType_Type_BOOLEAN;
  static constexpr Type CHAR = SerializableDataType_Type_CHAR;
  static constexpr Type UNDEFINED = SerializableDataType_Type_UNDEFINED;
  static constexpr Type VARSIZED = SerializableDataType_Type_VARSIZED;
  static inline bool Type_IsValid(int value) {
    return SerializableDataType_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = SerializableDataType_Type_Type_MIN;
  static constexpr Type Type_MAX = SerializableDataType_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = SerializableDataType_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* Type_descriptor() {
    return SerializableDataType_Type_descriptor();
  }
  template <typename T>
  static inline const std::string& Type_Name(T value) {
    return SerializableDataType_Type_Name(value);
  }
  static inline bool Type_Parse(absl::string_view name, Type* value) {
    return SerializableDataType_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kNullableFieldNumber = 2,
  };
  // .NES.SerializableDataType.Type type = 1;
  void clear_type() ;
  ::NES::SerializableDataType_Type type() const;
  void set_type(::NES::SerializableDataType_Type value);

  private:
  ::NES::SerializableDataType_Type _internal_type() const;
  void _internal_set_type(::NES::SerializableDataType_Type value);

  public:
  // bool nullable = 2;
  void clear_nullable() ;
  bool nullable() const;
  void set_nullable(bool value);

  private:
  bool _internal_nullable() const;
  void _internal_set_nullable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:NES.SerializableDataType)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SerializableDataType& from_msg);
    int type_;
    bool nullable_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SerializableDataType_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SerializableDataType

// .NES.SerializableDataType.Type type = 1;
inline void SerializableDataType::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::NES::SerializableDataType_Type SerializableDataType::type() const {
  // @@protoc_insertion_point(field_get:NES.SerializableDataType.type)
  return _internal_type();
}
inline void SerializableDataType::set_type(::NES::SerializableDataType_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:NES.SerializableDataType.type)
}
inline ::NES::SerializableDataType_Type SerializableDataType::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::NES::SerializableDataType_Type>(_impl_.type_);
}
inline void SerializableDataType::_internal_set_type(::NES::SerializableDataType_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bool nullable = 2;
inline void SerializableDataType::clear_nullable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nullable_ = false;
}
inline bool SerializableDataType::nullable() const {
  // @@protoc_insertion_point(field_get:NES.SerializableDataType.nullable)
  return _internal_nullable();
}
inline void SerializableDataType::set_nullable(bool value) {
  _internal_set_nullable(value);
  // @@protoc_insertion_point(field_set:NES.SerializableDataType.nullable)
}
inline bool SerializableDataType::_internal_nullable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nullable_;
}
inline void SerializableDataType::_internal_set_nullable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nullable_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NES


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::NES::SerializableDataType_Type> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NES::SerializableDataType_Type>() {
  return ::NES::SerializableDataType_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SerializableDataType_2eproto_2epb_2eh
