// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableVariantDescriptor.proto
// Protobuf C++ Version: 5.29.5

#include "SerializableVariantDescriptor.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NES {

inline constexpr SerializableEnumWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableEnumWrapper::SerializableEnumWrapper(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableEnumWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableEnumWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableEnumWrapperDefaultTypeInternal() {}
  union {
    SerializableEnumWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableEnumWrapperDefaultTypeInternal _SerializableEnumWrapper_default_instance_;

inline constexpr SerializableVariantDescriptor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableVariantDescriptor::SerializableVariantDescriptor(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableVariantDescriptorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableVariantDescriptorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableVariantDescriptorDefaultTypeInternal() {}
  union {
    SerializableVariantDescriptor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableVariantDescriptorDefaultTypeInternal _SerializableVariantDescriptor_default_instance_;
}  // namespace NES
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SerializableVariantDescriptor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SerializableVariantDescriptor_2eproto = nullptr;
const ::uint32_t
    TableStruct_SerializableVariantDescriptor_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableEnumWrapper, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableEnumWrapper, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableVariantDescriptor, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::NES::SerializableVariantDescriptor, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::NES::SerializableVariantDescriptor, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NES::SerializableEnumWrapper)},
        {9, -1, -1, sizeof(::NES::SerializableVariantDescriptor)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NES::_SerializableEnumWrapper_default_instance_._instance,
    &::NES::_SerializableVariantDescriptor_default_instance_._instance,
};
const char descriptor_table_protodef_SerializableVariantDescriptor_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#SerializableVariantDescriptor.proto\022\003N"
    "ES\"(\n\027SerializableEnumWrapper\022\r\n\005value\030\001"
    " \001(\t\"\247\002\n\035SerializableVariantDescriptor\022\023"
    "\n\tint_value\030\001 \001(\005H\000\022\024\n\nuint_value\030\002 \001(\rH"
    "\000\022\024\n\nlong_value\030\003 \001(\003H\000\022\025\n\013ulong_value\030\004"
    " \001(\004H\000\022\024\n\nbool_value\030\005 \001(\010H\000\022\024\n\nchar_val"
    "ue\030\006 \001(\007H\000\022\025\n\013float_value\030\007 \001(\002H\000\022\026\n\014dou"
    "ble_value\030\010 \001(\001H\000\022\026\n\014string_value\030\t \001(\tH"
    "\000\0222\n\nenum_value\030\n \001(\0132\034.NES.Serializable"
    "EnumWrapperH\000B\007\n\005valueb\006proto3"
};
static ::absl::once_flag descriptor_table_SerializableVariantDescriptor_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SerializableVariantDescriptor_2eproto = {
    false,
    false,
    390,
    descriptor_table_protodef_SerializableVariantDescriptor_2eproto,
    "SerializableVariantDescriptor.proto",
    &descriptor_table_SerializableVariantDescriptor_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_SerializableVariantDescriptor_2eproto::offsets,
    file_level_enum_descriptors_SerializableVariantDescriptor_2eproto,
    file_level_service_descriptors_SerializableVariantDescriptor_2eproto,
};
namespace NES {
// ===================================================================

class SerializableEnumWrapper::_Internal {
 public:
};

SerializableEnumWrapper::SerializableEnumWrapper(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableEnumWrapper)
}
inline PROTOBUF_NDEBUG_INLINE SerializableEnumWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableEnumWrapper& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

SerializableEnumWrapper::SerializableEnumWrapper(
    ::google::protobuf::Arena* arena,
    const SerializableEnumWrapper& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableEnumWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:NES.SerializableEnumWrapper)
}
inline PROTOBUF_NDEBUG_INLINE SerializableEnumWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void SerializableEnumWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SerializableEnumWrapper::~SerializableEnumWrapper() {
  // @@protoc_insertion_point(destructor:NES.SerializableEnumWrapper)
  SharedDtor(*this);
}
inline void SerializableEnumWrapper::SharedDtor(MessageLite& self) {
  SerializableEnumWrapper& this_ = static_cast<SerializableEnumWrapper&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SerializableEnumWrapper::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableEnumWrapper(arena);
}
constexpr auto SerializableEnumWrapper::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SerializableEnumWrapper),
                                            alignof(SerializableEnumWrapper));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableEnumWrapper::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableEnumWrapper_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableEnumWrapper::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableEnumWrapper>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableEnumWrapper::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableEnumWrapper>(), &SerializableEnumWrapper::ByteSizeLong,
            &SerializableEnumWrapper::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableEnumWrapper, _impl_._cached_size_),
        false,
    },
    &SerializableEnumWrapper::kDescriptorMethods,
    &descriptor_table_SerializableVariantDescriptor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableEnumWrapper::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2> SerializableEnumWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableEnumWrapper>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableEnumWrapper, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableEnumWrapper, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\5\0\0\0\0\0\0"
    "NES.SerializableEnumWrapper"
    "value"
  }},
};

PROTOBUF_NOINLINE void SerializableEnumWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableEnumWrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableEnumWrapper::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableEnumWrapper& this_ = static_cast<const SerializableEnumWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableEnumWrapper::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableEnumWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableEnumWrapper)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string value = 1;
          if (!this_._internal_value().empty()) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableEnumWrapper.value");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableEnumWrapper)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableEnumWrapper::ByteSizeLong(const MessageLite& base) {
          const SerializableEnumWrapper& this_ = static_cast<const SerializableEnumWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableEnumWrapper::ByteSizeLong() const {
          const SerializableEnumWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableEnumWrapper)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string value = 1;
            if (!this_._internal_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableEnumWrapper::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableEnumWrapper*>(&to_msg);
  auto& from = static_cast<const SerializableEnumWrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableEnumWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableEnumWrapper::CopyFrom(const SerializableEnumWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableEnumWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableEnumWrapper::InternalSwap(SerializableEnumWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata SerializableEnumWrapper::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SerializableVariantDescriptor::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::NES::SerializableVariantDescriptor, _impl_._oneof_case_);
};

void SerializableVariantDescriptor::set_allocated_enum_value(::NES::SerializableEnumWrapper* enum_value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_value();
  if (enum_value) {
    ::google::protobuf::Arena* submessage_arena = enum_value->GetArena();
    if (message_arena != submessage_arena) {
      enum_value = ::google::protobuf::internal::GetOwnedMessage(message_arena, enum_value, submessage_arena);
    }
    set_has_enum_value();
    _impl_.value_.enum_value_ = enum_value;
  }
  // @@protoc_insertion_point(field_set_allocated:NES.SerializableVariantDescriptor.enum_value)
}
SerializableVariantDescriptor::SerializableVariantDescriptor(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableVariantDescriptor)
}
inline PROTOBUF_NDEBUG_INLINE SerializableVariantDescriptor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableVariantDescriptor& from_msg)
      : value_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

SerializableVariantDescriptor::SerializableVariantDescriptor(
    ::google::protobuf::Arena* arena,
    const SerializableVariantDescriptor& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableVariantDescriptor* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kIntValue:
        _impl_.value_.int_value_ = from._impl_.value_.int_value_;
        break;
      case kUintValue:
        _impl_.value_.uint_value_ = from._impl_.value_.uint_value_;
        break;
      case kLongValue:
        _impl_.value_.long_value_ = from._impl_.value_.long_value_;
        break;
      case kUlongValue:
        _impl_.value_.ulong_value_ = from._impl_.value_.ulong_value_;
        break;
      case kBoolValue:
        _impl_.value_.bool_value_ = from._impl_.value_.bool_value_;
        break;
      case kCharValue:
        _impl_.value_.char_value_ = from._impl_.value_.char_value_;
        break;
      case kFloatValue:
        _impl_.value_.float_value_ = from._impl_.value_.float_value_;
        break;
      case kDoubleValue:
        _impl_.value_.double_value_ = from._impl_.value_.double_value_;
        break;
      case kStringValue:
        new (&_impl_.value_.string_value_) decltype(_impl_.value_.string_value_){arena, from._impl_.value_.string_value_};
        break;
      case kEnumValue:
        _impl_.value_.enum_value_ = ::google::protobuf::Message::CopyConstruct<::NES::SerializableEnumWrapper>(arena, *from._impl_.value_.enum_value_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:NES.SerializableVariantDescriptor)
}
inline PROTOBUF_NDEBUG_INLINE SerializableVariantDescriptor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void SerializableVariantDescriptor::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SerializableVariantDescriptor::~SerializableVariantDescriptor() {
  // @@protoc_insertion_point(destructor:NES.SerializableVariantDescriptor)
  SharedDtor(*this);
}
inline void SerializableVariantDescriptor::SharedDtor(MessageLite& self) {
  SerializableVariantDescriptor& this_ = static_cast<SerializableVariantDescriptor&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_value()) {
    this_.clear_value();
  }
  this_._impl_.~Impl_();
}

void SerializableVariantDescriptor::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:NES.SerializableVariantDescriptor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (value_case()) {
    case kIntValue: {
      // No need to clear
      break;
    }
    case kUintValue: {
      // No need to clear
      break;
    }
    case kLongValue: {
      // No need to clear
      break;
    }
    case kUlongValue: {
      // No need to clear
      break;
    }
    case kBoolValue: {
      // No need to clear
      break;
    }
    case kCharValue: {
      // No need to clear
      break;
    }
    case kFloatValue: {
      // No need to clear
      break;
    }
    case kDoubleValue: {
      // No need to clear
      break;
    }
    case kStringValue: {
      _impl_.value_.string_value_.Destroy();
      break;
    }
    case kEnumValue: {
      if (GetArena() == nullptr) {
        delete _impl_.value_.enum_value_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.value_.enum_value_);
      }
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


inline void* SerializableVariantDescriptor::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableVariantDescriptor(arena);
}
constexpr auto SerializableVariantDescriptor::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SerializableVariantDescriptor),
                                            alignof(SerializableVariantDescriptor));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableVariantDescriptor::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableVariantDescriptor_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableVariantDescriptor::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableVariantDescriptor>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableVariantDescriptor::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableVariantDescriptor>(), &SerializableVariantDescriptor::ByteSizeLong,
            &SerializableVariantDescriptor::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_._cached_size_),
        false,
    },
    &SerializableVariantDescriptor::kDescriptorMethods,
    &descriptor_table_SerializableVariantDescriptor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableVariantDescriptor::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 10, 1, 62, 2> SerializableVariantDescriptor::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableVariantDescriptor>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 int_value = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.int_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // uint32 uint_value = 2;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.uint_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt32)},
    // int64 long_value = 3;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.long_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kInt64)},
    // uint64 ulong_value = 4;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.ulong_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUInt64)},
    // bool bool_value = 5;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.bool_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // fixed32 char_value = 6;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.char_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFixed32)},
    // float float_value = 7;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.float_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kFloat)},
    // double double_value = 8;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.double_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // string string_value = 9;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.string_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .NES.SerializableEnumWrapper enum_value = 10;
    {PROTOBUF_FIELD_OFFSET(SerializableVariantDescriptor, _impl_.value_.enum_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::NES::SerializableEnumWrapper>()},
  }}, {{
    "\41\0\0\0\0\0\0\0\0\14\0\0\0\0\0\0"
    "NES.SerializableVariantDescriptor"
    "string_value"
  }},
};

PROTOBUF_NOINLINE void SerializableVariantDescriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableVariantDescriptor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_value();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableVariantDescriptor::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableVariantDescriptor& this_ = static_cast<const SerializableVariantDescriptor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableVariantDescriptor::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableVariantDescriptor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableVariantDescriptor)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.value_case()) {
            case kIntValue: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt32ToArrayWithField<1>(
                      stream, this_._internal_int_value(), target);
              break;
            }
            case kUintValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                  2, this_._internal_uint_value(), target);
              break;
            }
            case kLongValue: {
              target = ::google::protobuf::internal::WireFormatLite::
                  WriteInt64ToArrayWithField<3>(
                      stream, this_._internal_long_value(), target);
              break;
            }
            case kUlongValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                  4, this_._internal_ulong_value(), target);
              break;
            }
            case kBoolValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteBoolToArray(
                  5, this_._internal_bool_value(), target);
              break;
            }
            case kCharValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                  6, this_._internal_char_value(), target);
              break;
            }
            case kFloatValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteFloatToArray(
                  7, this_._internal_float_value(), target);
              break;
            }
            case kDoubleValue: {
              target = stream->EnsureSpace(target);
              target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                  8, this_._internal_double_value(), target);
              break;
            }
            case kStringValue: {
              const std::string& _s = this_._internal_string_value();
              ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                  _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableVariantDescriptor.string_value");
              target = stream->WriteStringMaybeAliased(9, _s, target);
              break;
            }
            case kEnumValue: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  10, *this_._impl_.value_.enum_value_, this_._impl_.value_.enum_value_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableVariantDescriptor)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableVariantDescriptor::ByteSizeLong(const MessageLite& base) {
          const SerializableVariantDescriptor& this_ = static_cast<const SerializableVariantDescriptor&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableVariantDescriptor::ByteSizeLong() const {
          const SerializableVariantDescriptor& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableVariantDescriptor)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.value_case()) {
            // int32 int_value = 1;
            case kIntValue: {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_int_value());
              break;
            }
            // uint32 uint_value = 2;
            case kUintValue: {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_uint_value());
              break;
            }
            // int64 long_value = 3;
            case kLongValue: {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_long_value());
              break;
            }
            // uint64 ulong_value = 4;
            case kUlongValue: {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_ulong_value());
              break;
            }
            // bool bool_value = 5;
            case kBoolValue: {
              total_size += 2;
              break;
            }
            // fixed32 char_value = 6;
            case kCharValue: {
              total_size += 5;
              break;
            }
            // float float_value = 7;
            case kFloatValue: {
              total_size += 5;
              break;
            }
            // double double_value = 8;
            case kDoubleValue: {
              total_size += 9;
              break;
            }
            // string string_value = 9;
            case kStringValue: {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_string_value());
              break;
            }
            // .NES.SerializableEnumWrapper enum_value = 10;
            case kEnumValue: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.value_.enum_value_);
              break;
            }
            case VALUE_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableVariantDescriptor::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableVariantDescriptor*>(&to_msg);
  auto& from = static_cast<const SerializableVariantDescriptor&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableVariantDescriptor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_value();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kIntValue: {
        _this->_impl_.value_.int_value_ = from._impl_.value_.int_value_;
        break;
      }
      case kUintValue: {
        _this->_impl_.value_.uint_value_ = from._impl_.value_.uint_value_;
        break;
      }
      case kLongValue: {
        _this->_impl_.value_.long_value_ = from._impl_.value_.long_value_;
        break;
      }
      case kUlongValue: {
        _this->_impl_.value_.ulong_value_ = from._impl_.value_.ulong_value_;
        break;
      }
      case kBoolValue: {
        _this->_impl_.value_.bool_value_ = from._impl_.value_.bool_value_;
        break;
      }
      case kCharValue: {
        _this->_impl_.value_.char_value_ = from._impl_.value_.char_value_;
        break;
      }
      case kFloatValue: {
        _this->_impl_.value_.float_value_ = from._impl_.value_.float_value_;
        break;
      }
      case kDoubleValue: {
        _this->_impl_.value_.double_value_ = from._impl_.value_.double_value_;
        break;
      }
      case kStringValue: {
        if (oneof_needs_init) {
          _this->_impl_.value_.string_value_.InitDefault();
        }
        _this->_impl_.value_.string_value_.Set(from._internal_string_value(), arena);
        break;
      }
      case kEnumValue: {
        if (oneof_needs_init) {
          _this->_impl_.value_.enum_value_ =
              ::google::protobuf::Message::CopyConstruct<::NES::SerializableEnumWrapper>(arena, *from._impl_.value_.enum_value_);
        } else {
          _this->_impl_.value_.enum_value_->MergeFrom(from._internal_enum_value());
        }
        break;
      }
      case VALUE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableVariantDescriptor::CopyFrom(const SerializableVariantDescriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableVariantDescriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableVariantDescriptor::InternalSwap(SerializableVariantDescriptor* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata SerializableVariantDescriptor::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SerializableVariantDescriptor_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
