// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SerializableDataType.proto

#ifndef GRPC_MOCK_SerializableDataType_2eproto__INCLUDED
#define GRPC_MOCK_SerializableDataType_2eproto__INCLUDED

#include "SerializableDataType.pb.h"
#include "SerializableDataType.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace NES {

}  // namespace NES


#endif  // GRPC_MOCK_SerializableDataType_2eproto__INCLUDED
