// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SerializableQueryPlan.proto
// Protobuf C++ Version: 5.29.5

#include "SerializableQueryPlan.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NES {

inline constexpr SerializableQueryPlan::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reflectedoperators_{},
        rootoperatorids_{},
        _rootoperatorids_cached_byte_size_{0},
        queryid_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SerializableQueryPlan::SerializableQueryPlan(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializableQueryPlanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializableQueryPlanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializableQueryPlanDefaultTypeInternal() {}
  union {
    SerializableQueryPlan _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializableQueryPlanDefaultTypeInternal _SerializableQueryPlan_default_instance_;
}  // namespace NES
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SerializableQueryPlan_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SerializableQueryPlan_2eproto = nullptr;
const ::uint32_t
    TableStruct_SerializableQueryPlan_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryPlan, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryPlan, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryPlan, _impl_.reflectedoperators_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryPlan, _impl_.rootoperatorids_),
        PROTOBUF_FIELD_OFFSET(::NES::SerializableQueryPlan, _impl_.queryid_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::NES::SerializableQueryPlan)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::NES::_SerializableQueryPlan_default_instance_._instance,
};
const char descriptor_table_protodef_SerializableQueryPlan_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033SerializableQueryPlan.proto\022\003NES\032\031Seri"
    "alizableQueryId.proto\"\210\001\n\025SerializableQu"
    "eryPlan\022\032\n\022reflectedOperators\030\001 \003(\t\022\027\n\017r"
    "ootOperatorIds\030\002 \003(\004\022.\n\007queryId\030\003 \001(\0132\030."
    "NES.SerializableQueryIdH\000\210\001\001B\n\n\010_queryId"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_SerializableQueryPlan_2eproto_deps[1] =
    {
        &::descriptor_table_SerializableQueryId_2eproto,
};
static ::absl::once_flag descriptor_table_SerializableQueryPlan_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SerializableQueryPlan_2eproto = {
    false,
    false,
    208,
    descriptor_table_protodef_SerializableQueryPlan_2eproto,
    "SerializableQueryPlan.proto",
    &descriptor_table_SerializableQueryPlan_2eproto_once,
    descriptor_table_SerializableQueryPlan_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_SerializableQueryPlan_2eproto::offsets,
    file_level_enum_descriptors_SerializableQueryPlan_2eproto,
    file_level_service_descriptors_SerializableQueryPlan_2eproto,
};
namespace NES {
// ===================================================================

class SerializableQueryPlan::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SerializableQueryPlan>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_._has_bits_);
};

void SerializableQueryPlan::clear_queryid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.queryid_ != nullptr) _impl_.queryid_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
SerializableQueryPlan::SerializableQueryPlan(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NES.SerializableQueryPlan)
}
inline PROTOBUF_NDEBUG_INLINE SerializableQueryPlan::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NES::SerializableQueryPlan& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reflectedoperators_{visibility, arena, from.reflectedoperators_},
        rootoperatorids_{visibility, arena, from.rootoperatorids_},
        _rootoperatorids_cached_byte_size_{0} {}

SerializableQueryPlan::SerializableQueryPlan(
    ::google::protobuf::Arena* arena,
    const SerializableQueryPlan& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializableQueryPlan* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.queryid_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::NES::SerializableQueryId>(
                              arena, *from._impl_.queryid_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:NES.SerializableQueryPlan)
}
inline PROTOBUF_NDEBUG_INLINE SerializableQueryPlan::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        reflectedoperators_{visibility, arena},
        rootoperatorids_{visibility, arena},
        _rootoperatorids_cached_byte_size_{0} {}

inline void SerializableQueryPlan::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.queryid_ = {};
}
SerializableQueryPlan::~SerializableQueryPlan() {
  // @@protoc_insertion_point(destructor:NES.SerializableQueryPlan)
  SharedDtor(*this);
}
inline void SerializableQueryPlan::SharedDtor(MessageLite& self) {
  SerializableQueryPlan& this_ = static_cast<SerializableQueryPlan&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.queryid_;
  this_._impl_.~Impl_();
}

inline void* SerializableQueryPlan::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SerializableQueryPlan(arena);
}
constexpr auto SerializableQueryPlan::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.reflectedoperators_) +
          decltype(SerializableQueryPlan::_impl_.reflectedoperators_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.rootoperatorids_) +
          decltype(SerializableQueryPlan::_impl_.rootoperatorids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SerializableQueryPlan), alignof(SerializableQueryPlan), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SerializableQueryPlan::PlacementNew_,
                                 sizeof(SerializableQueryPlan),
                                 alignof(SerializableQueryPlan));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SerializableQueryPlan::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SerializableQueryPlan_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SerializableQueryPlan::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SerializableQueryPlan>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SerializableQueryPlan::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SerializableQueryPlan>(), &SerializableQueryPlan::ByteSizeLong,
            &SerializableQueryPlan::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_._cached_size_),
        false,
    },
    &SerializableQueryPlan::kDescriptorMethods,
    &descriptor_table_SerializableQueryPlan_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SerializableQueryPlan::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 52, 2> SerializableQueryPlan::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NES::SerializableQueryPlan>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated string reflectedOperators = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.reflectedoperators_)}},
    // repeated uint64 rootOperatorIds = 2;
    {::_pbi::TcParser::FastV64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.rootoperatorids_)}},
    // optional .NES.SerializableQueryId queryId = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.queryid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string reflectedOperators = 1;
    {PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.reflectedoperators_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated uint64 rootOperatorIds = 2;
    {PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.rootoperatorids_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // optional .NES.SerializableQueryId queryId = 3;
    {PROTOBUF_FIELD_OFFSET(SerializableQueryPlan, _impl_.queryid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::NES::SerializableQueryId>()},
  }}, {{
    "\31\22\0\0\0\0\0\0"
    "NES.SerializableQueryPlan"
    "reflectedOperators"
  }},
};

PROTOBUF_NOINLINE void SerializableQueryPlan::Clear() {
// @@protoc_insertion_point(message_clear_start:NES.SerializableQueryPlan)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reflectedoperators_.Clear();
  _impl_.rootoperatorids_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.queryid_ != nullptr);
    _impl_.queryid_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SerializableQueryPlan::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SerializableQueryPlan& this_ = static_cast<const SerializableQueryPlan&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SerializableQueryPlan::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SerializableQueryPlan& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NES.SerializableQueryPlan)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string reflectedOperators = 1;
          for (int i = 0, n = this_._internal_reflectedoperators_size(); i < n; ++i) {
            const auto& s = this_._internal_reflectedoperators().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NES.SerializableQueryPlan.reflectedOperators");
            target = stream->WriteString(1, s, target);
          }

          // repeated uint64 rootOperatorIds = 2;
          {
            int byte_size = this_._impl_._rootoperatorids_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt64Packed(
                  2, this_._internal_rootoperatorids(), byte_size, target);
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .NES.SerializableQueryId queryId = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.queryid_, this_._impl_.queryid_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NES.SerializableQueryPlan)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SerializableQueryPlan::ByteSizeLong(const MessageLite& base) {
          const SerializableQueryPlan& this_ = static_cast<const SerializableQueryPlan&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SerializableQueryPlan::ByteSizeLong() const {
          const SerializableQueryPlan& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NES.SerializableQueryPlan)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string reflectedOperators = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_reflectedoperators().size());
              for (int i = 0, n = this_._internal_reflectedoperators().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_reflectedoperators().Get(i));
              }
            }
            // repeated uint64 rootOperatorIds = 2;
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
                      this_._internal_rootoperatorids(), 1,
                      this_._impl_._rootoperatorids_cached_byte_size_);
            }
          }
           {
            // optional .NES.SerializableQueryId queryId = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.queryid_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SerializableQueryPlan::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializableQueryPlan*>(&to_msg);
  auto& from = static_cast<const SerializableQueryPlan&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NES.SerializableQueryPlan)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_reflectedoperators()->MergeFrom(from._internal_reflectedoperators());
  _this->_internal_mutable_rootoperatorids()->MergeFrom(from._internal_rootoperatorids());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.queryid_ != nullptr);
    if (_this->_impl_.queryid_ == nullptr) {
      _this->_impl_.queryid_ =
          ::google::protobuf::Message::CopyConstruct<::NES::SerializableQueryId>(arena, *from._impl_.queryid_);
    } else {
      _this->_impl_.queryid_->MergeFrom(*from._impl_.queryid_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializableQueryPlan::CopyFrom(const SerializableQueryPlan& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NES.SerializableQueryPlan)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializableQueryPlan::InternalSwap(SerializableQueryPlan* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.reflectedoperators_.InternalSwap(&other->_impl_.reflectedoperators_);
  _impl_.rootoperatorids_.InternalSwap(&other->_impl_.rootoperatorids_);
  swap(_impl_.queryid_, other->_impl_.queryid_);
}

::google::protobuf::Metadata SerializableQueryPlan::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NES
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SerializableQueryPlan_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
