// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SingleNodeWorkerRPCService.proto

#ifndef GRPC_MOCK_SingleNodeWorkerRPCService_2eproto__INCLUDED
#define GRPC_MOCK_SingleNodeWorkerRPCService_2eproto__INCLUDED

#include "SingleNodeWorkerRPCService.pb.h"
#include "SingleNodeWorkerRPCService.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>

class MockWorkerRPCServiceStub : public WorkerRPCService::StubInterface {
 public:
  MOCK_METHOD3(RegisterQuery, ::grpc::Status(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::RegisterQueryReply* response));
  MOCK_METHOD3(AsyncRegisterQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>*(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncRegisterQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>*(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(StartQuery, ::grpc::Status(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::google::protobuf::Empty* response));
  MOCK_METHOD3(AsyncStartQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>*(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncStartQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>*(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(StopQuery, ::grpc::Status(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::google::protobuf::Empty* response));
  MOCK_METHOD3(AsyncStopQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>*(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncStopQueryRaw, ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>*(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(RequestQueryStatus, ::grpc::Status(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::QueryStatusReply* response));
  MOCK_METHOD3(AsyncRequestQueryStatusRaw, ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>*(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncRequestQueryStatusRaw, ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>*(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(RequestStatus, ::grpc::Status(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::WorkerStatusResponse* response));
  MOCK_METHOD3(AsyncRequestStatusRaw, ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>*(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncRequestStatusRaw, ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>*(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq));
};


#endif  // GRPC_MOCK_SingleNodeWorkerRPCService_2eproto__INCLUDED
