// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SingleNodeWorkerRPCService.proto
// Original file comments:
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_SingleNodeWorkerRPCService_2eproto__INCLUDED
#define GRPC_SingleNodeWorkerRPCService_2eproto__INCLUDED

#include "SingleNodeWorkerRPCService.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class WorkerRPCService final {
 public:
  static constexpr char const* service_full_name() {
    return "WorkerRPCService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::RegisterQueryReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>> AsyncRegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>>(AsyncRegisterQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>> PrepareAsyncRegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>>(PrepareAsyncRegisterQueryRaw(context, request, cq));
    }
    virtual ::grpc::Status StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncStartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncStartQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncStartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncStartQueryRaw(context, request, cq));
    }
    virtual ::grpc::Status StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncStopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncStopQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncStopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncStopQueryRaw(context, request, cq));
    }
    virtual ::grpc::Status RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::QueryStatusReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>> AsyncRequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>>(AsyncRequestQueryStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>> PrepareAsyncRequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>>(PrepareAsyncRequestQueryStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::WorkerStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>> AsyncRequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>>(AsyncRequestStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>> PrepareAsyncRequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>>(PrepareAsyncRequestStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>* AsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RegisterQueryReply>* PrepareAsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>* AsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::QueryStatusReply>* PrepareAsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>* AsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WorkerStatusResponse>* PrepareAsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::RegisterQueryReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>> AsyncRegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>>(AsyncRegisterQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>> PrepareAsyncRegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>>(PrepareAsyncRegisterQueryRaw(context, request, cq));
    }
    ::grpc::Status StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncStartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncStartQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncStartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncStartQueryRaw(context, request, cq));
    }
    ::grpc::Status StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncStopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncStopQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncStopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncStopQueryRaw(context, request, cq));
    }
    ::grpc::Status RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::QueryStatusReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>> AsyncRequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>>(AsyncRequestQueryStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>> PrepareAsyncRequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>>(PrepareAsyncRequestQueryStatusRaw(context, request, cq));
    }
    ::grpc::Status RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::WorkerStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>> AsyncRequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>>(AsyncRequestStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>> PrepareAsyncRequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>>(PrepareAsyncRequestStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, std::function<void(::grpc::Status)>) override;
      void RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>* AsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>* PrepareAsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>* AsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::QueryStatusReply>* PrepareAsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>* AsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>* PrepareAsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_StartQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_StopQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_RequestQueryStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_RequestStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterQuery(::grpc::ServerContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response);
    virtual ::grpc::Status StartQuery(::grpc::ServerContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response);
    virtual ::grpc::Status StopQuery(::grpc::ServerContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response);
    virtual ::grpc::Status RequestQueryStatus(::grpc::ServerContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response);
    virtual ::grpc::Status RequestStatus(::grpc::ServerContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterQuery(::grpc::ServerContext* context, ::RegisterQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::RegisterQueryReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartQuery() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartQuery(::grpc::ServerContext* context, ::StartQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopQuery() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopQuery(::grpc::ServerContext* context, ::StopQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestQueryStatus(::grpc::ServerContext* context, ::QueryStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::QueryStatusReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestStatus() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestStatus(::grpc::ServerContext* context, ::WorkerStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::WorkerStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterQuery<WithAsyncMethod_StartQuery<WithAsyncMethod_StopQuery<WithAsyncMethod_RequestQueryStatus<WithAsyncMethod_RequestStatus<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RegisterQueryRequest, ::RegisterQueryReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response) { return this->RegisterQuery(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterQuery(
        ::grpc::MessageAllocator< ::RegisterQueryRequest, ::RegisterQueryReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RegisterQueryRequest, ::RegisterQueryReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartQuery() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::StartQueryRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response) { return this->StartQuery(context, request, response); }));}
    void SetMessageAllocatorFor_StartQuery(
        ::grpc::MessageAllocator< ::StartQueryRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::StartQueryRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StopQuery() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::StopQueryRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response) { return this->StopQuery(context, request, response); }));}
    void SetMessageAllocatorFor_StopQuery(
        ::grpc::MessageAllocator< ::StopQueryRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::StopQueryRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::QueryStatusRequest, ::QueryStatusReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response) { return this->RequestQueryStatus(context, request, response); }));}
    void SetMessageAllocatorFor_RequestQueryStatus(
        ::grpc::MessageAllocator< ::QueryStatusRequest, ::QueryStatusReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::QueryStatusRequest, ::QueryStatusReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestQueryStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestStatus() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::WorkerStatusRequest, ::WorkerStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response) { return this->RequestStatus(context, request, response); }));}
    void SetMessageAllocatorFor_RequestStatus(
        ::grpc::MessageAllocator< ::WorkerStatusRequest, ::WorkerStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WorkerStatusRequest, ::WorkerStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterQuery<WithCallbackMethod_StartQuery<WithCallbackMethod_StopQuery<WithCallbackMethod_RequestQueryStatus<WithCallbackMethod_RequestStatus<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartQuery() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopQuery() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestStatus() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartQuery() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopQuery() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestQueryStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestStatus() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartQuery() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StopQuery() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestQueryStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestQueryStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestStatus() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterQuery() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RegisterQueryRequest, ::RegisterQueryReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RegisterQueryRequest, ::RegisterQueryReply>* streamer) {
                       return this->StreamedRegisterQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterQuery(::grpc::ServerContext* /*context*/, const ::RegisterQueryRequest* /*request*/, ::RegisterQueryReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RegisterQueryRequest,::RegisterQueryReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartQuery() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::StartQueryRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::StartQueryRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedStartQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartQuery(::grpc::ServerContext* /*context*/, const ::StartQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::StartQueryRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopQuery() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::StopQueryRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::StopQueryRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedStopQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopQuery(::grpc::ServerContext* /*context*/, const ::StopQueryRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::StopQueryRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestQueryStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestQueryStatus() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::QueryStatusRequest, ::QueryStatusReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::QueryStatusRequest, ::QueryStatusReply>* streamer) {
                       return this->StreamedRequestQueryStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestQueryStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestQueryStatus(::grpc::ServerContext* /*context*/, const ::QueryStatusRequest* /*request*/, ::QueryStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestQueryStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::QueryStatusRequest,::QueryStatusReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestStatus() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WorkerStatusRequest, ::WorkerStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WorkerStatusRequest, ::WorkerStatusResponse>* streamer) {
                       return this->StreamedRequestStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestStatus(::grpc::ServerContext* /*context*/, const ::WorkerStatusRequest* /*request*/, ::WorkerStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WorkerStatusRequest,::WorkerStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterQuery<WithStreamedUnaryMethod_StartQuery<WithStreamedUnaryMethod_StopQuery<WithStreamedUnaryMethod_RequestQueryStatus<WithStreamedUnaryMethod_RequestStatus<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterQuery<WithStreamedUnaryMethod_StartQuery<WithStreamedUnaryMethod_StopQuery<WithStreamedUnaryMethod_RequestQueryStatus<WithStreamedUnaryMethod_RequestStatus<Service > > > > > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_SingleNodeWorkerRPCService_2eproto__INCLUDED
