// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SingleNodeWorkerRPCService.proto

#include "SingleNodeWorkerRPCService.pb.h"
#include "SingleNodeWorkerRPCService.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* WorkerRPCService_method_names[] = {
  "/WorkerRPCService/RegisterQuery",
  "/WorkerRPCService/StartQuery",
  "/WorkerRPCService/StopQuery",
  "/WorkerRPCService/RequestQueryStatus",
  "/WorkerRPCService/RequestStatus",
};

std::unique_ptr< WorkerRPCService::Stub> WorkerRPCService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerRPCService::Stub> stub(new WorkerRPCService::Stub(channel, options));
  return stub;
}

WorkerRPCService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterQuery_(WorkerRPCService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartQuery_(WorkerRPCService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopQuery_(WorkerRPCService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestQueryStatus_(WorkerRPCService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestStatus_(WorkerRPCService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerRPCService::Stub::RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::RegisterQueryReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RegisterQueryRequest, ::RegisterQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterQuery_, context, request, response);
}

void WorkerRPCService::Stub::async::RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RegisterQueryRequest, ::RegisterQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterQuery_, context, request, response, std::move(f));
}

void WorkerRPCService::Stub::async::RegisterQuery(::grpc::ClientContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>* WorkerRPCService::Stub::PrepareAsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RegisterQueryReply, ::RegisterQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RegisterQueryReply>* WorkerRPCService::Stub::AsyncRegisterQueryRaw(::grpc::ClientContext* context, const ::RegisterQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerRPCService::Stub::StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StartQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartQuery_, context, request, response);
}

void WorkerRPCService::Stub::async::StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StartQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartQuery_, context, request, response, std::move(f));
}

void WorkerRPCService::Stub::async::StartQuery(::grpc::ClientContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerRPCService::Stub::PrepareAsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::StartQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerRPCService::Stub::AsyncStartQueryRaw(::grpc::ClientContext* context, const ::StartQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerRPCService::Stub::StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StopQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopQuery_, context, request, response);
}

void WorkerRPCService::Stub::async::StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StopQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopQuery_, context, request, response, std::move(f));
}

void WorkerRPCService::Stub::async::StopQuery(::grpc::ClientContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerRPCService::Stub::PrepareAsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::StopQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WorkerRPCService::Stub::AsyncStopQueryRaw(::grpc::ClientContext* context, const ::StopQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerRPCService::Stub::RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::QueryStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::QueryStatusRequest, ::QueryStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestQueryStatus_, context, request, response);
}

void WorkerRPCService::Stub::async::RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::QueryStatusRequest, ::QueryStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestQueryStatus_, context, request, response, std::move(f));
}

void WorkerRPCService::Stub::async::RequestQueryStatus(::grpc::ClientContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestQueryStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::QueryStatusReply>* WorkerRPCService::Stub::PrepareAsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::QueryStatusReply, ::QueryStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestQueryStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::QueryStatusReply>* WorkerRPCService::Stub::AsyncRequestQueryStatusRaw(::grpc::ClientContext* context, const ::QueryStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestQueryStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerRPCService::Stub::RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::WorkerStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::WorkerStatusRequest, ::WorkerStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestStatus_, context, request, response);
}

void WorkerRPCService::Stub::async::RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::WorkerStatusRequest, ::WorkerStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestStatus_, context, request, response, std::move(f));
}

void WorkerRPCService::Stub::async::RequestStatus(::grpc::ClientContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>* WorkerRPCService::Stub::PrepareAsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::WorkerStatusResponse, ::WorkerStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::WorkerStatusResponse>* WorkerRPCService::Stub::AsyncRequestStatusRaw(::grpc::ClientContext* context, const ::WorkerStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerRPCService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRPCService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRPCService::Service, ::RegisterQueryRequest, ::RegisterQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RegisterQueryRequest* req,
             ::RegisterQueryReply* resp) {
               return service->RegisterQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRPCService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRPCService::Service, ::StartQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StartQueryRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->StartQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRPCService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRPCService::Service, ::StopQueryRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StopQueryRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->StopQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRPCService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRPCService::Service, ::QueryStatusRequest, ::QueryStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::QueryStatusRequest* req,
             ::QueryStatusReply* resp) {
               return service->RequestQueryStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRPCService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRPCService::Service, ::WorkerStatusRequest, ::WorkerStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRPCService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::WorkerStatusRequest* req,
             ::WorkerStatusResponse* resp) {
               return service->RequestStatus(ctx, req, resp);
             }, this)));
}

WorkerRPCService::Service::~Service() {
}

::grpc::Status WorkerRPCService::Service::RegisterQuery(::grpc::ServerContext* context, const ::RegisterQueryRequest* request, ::RegisterQueryReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerRPCService::Service::StartQuery(::grpc::ServerContext* context, const ::StartQueryRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerRPCService::Service::StopQuery(::grpc::ServerContext* context, const ::StopQueryRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerRPCService::Service::RequestQueryStatus(::grpc::ServerContext* context, const ::QueryStatusRequest* request, ::QueryStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerRPCService::Service::RequestStatus(::grpc::ServerContext* context, const ::WorkerStatusRequest* request, ::WorkerStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


