/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

/// NOLINT(clang-diagnostic-error)
#ifndef INCLUDED_FROM_REGISTRY_AGGREGATION_PHYSICAL_FUNCTION
#    error "This file should not be included directly! Include instead include <AggregationPhysicalFunctionRegistry.hpp>"
#endif

#include <memory>
#include <string>
#include <vector>
#include <Aggregation/Function/AggregationPhysicalFunction.hpp>
#include <Util/Registry.hpp>

namespace NES::AggregationPhysicalFunctionGeneratedRegistrar
{

/// declaration of register functions for 'AggregationPhysicalFunctions'
AggregationPhysicalFunctionRegistryReturnType RegisterAvgAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);
AggregationPhysicalFunctionRegistryReturnType RegisterCountAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);
AggregationPhysicalFunctionRegistryReturnType RegisterMaxAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);
AggregationPhysicalFunctionRegistryReturnType RegisterMinAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);
AggregationPhysicalFunctionRegistryReturnType RegisterMedianAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);
AggregationPhysicalFunctionRegistryReturnType RegisterSumAggregationPhysicalFunction(AggregationPhysicalFunctionRegistryArguments);

}

namespace NES
{
template <>
inline void
Registrar<AggregationPhysicalFunctionRegistry, std::string, AggregationPhysicalFunctionRegistryReturnType, AggregationPhysicalFunctionRegistryArguments>::registerAll(
    [[maybe_unused]] Registry<Registrar>& registry)
{
    using namespace NES::AggregationPhysicalFunctionGeneratedRegistrar;
    registry.addEntry("Avg", RegisterAvgAggregationPhysicalFunction);
	registry.addEntry("Count", RegisterCountAggregationPhysicalFunction);
	registry.addEntry("Max", RegisterMaxAggregationPhysicalFunction);
	registry.addEntry("Min", RegisterMinAggregationPhysicalFunction);
	registry.addEntry("Median", RegisterMedianAggregationPhysicalFunction);
	registry.addEntry("Sum", RegisterSumAggregationPhysicalFunction);
	
}
}
