/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <array>
#include <cstddef>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <variant>
#include <vector>
#include <Functions/LogicalFunction.hpp>
#include <Operators/Windows/Aggregations/WindowAggregationLogicalFunction.hpp>
#include <Operators/Windows/JoinLogicalOperator.hpp>
#include <Plans/LogicalPlan.hpp>
#include <Sinks/SinkDescriptor.hpp>
#include <WindowTypes/Types/TimeBasedWindowType.hpp>

#include <Functions/UnboundFieldAccessLogicalFunction.hpp>
#include <Identifiers/Identifier.hpp>
#include <WindowTypes/Measures/TimeCharacteristic.hpp>
#include <CommonParserFunctions.hpp>

namespace NES::Parsers
{

class AntlrSQLHelper
{
    using Projection = std::pair<std::optional<Identifier>, LogicalFunction>;
    std::vector<LogicalFunction> whereClauses; ///where and having clauses need to be accessed in reverse
    std::vector<LogicalFunction> havingClauses;
    std::optional<Identifier> source;
    std::optional<std::pair<Identifier, ConfigMap>> inlineSourceConfig;
    std::vector<Projection> projectionBuilder;

public:
    /// Constructors
    AntlrSQLHelper() = default;

    /// Query plans generated by antlr sql query parser.
    std::vector<LogicalPlan> queryPlans;

    /// Flags used to determine which token we are currently parsing.
    bool isSelect = false;
    bool isWhereOrHaving = false;
    bool isFrom = false;
    bool isWindow = false;
    bool isArithmeticBinary = false;
    bool isJoinRelation = false;
    bool isSimpleCondition = true;
    bool isTimeBasedWindow = true;
    bool isSetOperation = false;
    bool isGroupBy = false;
    bool hasMultipleAttributes = false;
    bool hasUnnamedAggregation = false;
    bool asterisk = false;

    [[nodiscard]] bool isInFunctionCall() const { return not functionBuilder.empty(); }

    [[nodiscard]] bool isInAggFunction() const { return not windowAggs.empty(); }

    std::optional<Windowing::TimeBasedWindowType> windowType;
    std::vector<std::pair<WindowAggregationLogicalFunction, std::optional<Identifier>>> windowAggs;
    std::vector<SinkDescriptor> sinkDescriptor;
    std::vector<std::string> constantBuilder;
    std::vector<LogicalFunction> functionBuilder;
    std::vector<UnboundFieldAccessLogicalFunction> groupByFields;
    std::vector<Identifier> joinSources;
    std::vector<LogicalFunction> joinKeyRelationHelper;
    JoinLogicalOperator::JoinType joinType = JoinLogicalOperator::JoinType::INNER_JOIN;

    /// Utility variables to keep state between enter/exit parser function calls.
    size_t opBoolean{}; ///anonymous token enum in AntlrSQLLexer.h
    std::string opValue;
    std::optional<Identifier> newSourceName;
    std::optional<std::variant<Windowing::UnboundTimeCharacteristic, std::array<Windowing::UnboundTimeCharacteristic, 2>>> windowTimestamp;

    /// Utility variables used to keep track of the parsing state.
    int size{};
    int advanceBy{};
    size_t timeUnit{}; ///anonymous token enum in AntlrSQLLexer.h
    size_t timeUnitAdvanceBy{};
    std::optional<int> minimumCount;
    int implicitMapCountHelper = 0;

    /// Pre-aggregation projections for desugaring expressions inside aggregation functions.
    /// E.g., AVG(i + UINT64(1)) becomes: Projection(*, i + UINT64(1) AS _AGG_INPUT_0) → AVG(_AGG_INPUT_0).
    std::vector<Projection> preAggregationProjections;
    size_t aggExprCounter = 0;

    /// Flag set while parsing a MODEL_INFERENCE TVF source to suppress identifier capture as FROM source
    bool isModelInference = false;

    [[nodiscard]] std::vector<LogicalFunction>& getWhereClauses();
    [[nodiscard]] std::vector<LogicalFunction>& getHavingClauses();
    [[nodiscard]] std::vector<Projection>& getProjections();

    void addWhereClause(LogicalFunction expressionNode);
    void addHavingClause(LogicalFunction expressionNode);
    void setSource(Identifier sourceName);
    [[nodiscard]] std::optional<Identifier> getSource() const;
    void setInlineSource(const Identifier& type, const ConfigMap& parameters);
    [[nodiscard]] std::optional<std::pair<Identifier, ConfigMap>> getInlineSourceConfig();
    void addProjection(std::optional<Identifier>, LogicalFunction);
};
}
